/**
 * API Contracts for DEMO Mode - Strict TypeScript interfaces
 * Defines the contract for all mock services
 */

import type { 
  Case, Task, Client, Hearing, Court, Judge, Document, Employee, Folder 
} from '@/contexts/AppStateContext';
import type { 
  Contact, TaskBundle, TaskTemplate, StageFootprint, TimelineEntry 
} from '@/persistence/unifiedStore';

// Standard API Response wrapper
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

// Pagination interface
export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  pagination?: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// Base CRUD service interface
export interface CrudService<T, CreateData, UpdateData> {
  create(data: CreateData): Promise<ApiResponse<T>>;
  update(id: string, data: UpdateData): Promise<ApiResponse<T>>;
  delete(id: string): Promise<ApiResponse<void>>;
  getById(id: string): Promise<ApiResponse<T>>;
  getAll(): Promise<ApiResponse<T[]>>;
}

// Client service interface
export interface CreateClientData {
  name: string;
  type: 'Individual' | 'Company' | 'Partnership' | 'Trust' | 'Other';
  category?: 'Regular Dealer' | 'Composition' | 'Exporter' | 'Service' | 'Other';
  registrationNo?: string;
  gstin?: string;
  pan: string;
  address: any;
  jurisdiction?: any;
  assignedCAId: string;
  assignedCAName: string;
  status: 'Active' | 'Inactive';
}

export interface UpdateClientData extends Partial<CreateClientData> {}

export interface ClientService extends CrudService<Client, CreateClientData, UpdateClientData> {
  getContacts(clientId: string): Promise<ApiResponse<Contact[]>>;
  addContact(clientId: string, contact: Omit<Contact, 'id' | 'clientId' | 'createdAt' | 'updatedAt'>): Promise<ApiResponse<Contact>>;
  updateContact(clientId: string, contactId: string, updates: Partial<Contact>): Promise<ApiResponse<Contact>>;
  deleteContact(clientId: string, contactId: string): Promise<ApiResponse<void>>;
}

// Case service interface
export interface CreateCaseData {
  caseNumber: string;
  title: string;
  clientId: string;
  currentStage: 'Scrutiny' | 'Demand' | 'Adjudication' | 'Appeals' | 'GSTAT' | 'HC' | 'SC';
  priority: 'High' | 'Medium' | 'Low';
  assignedToId: string;
  assignedToName: string;
  description?: string;
  amountInDispute?: number;
}

export interface UpdateCaseData extends Partial<CreateCaseData> {}

export interface CaseService extends CrudService<Case, CreateCaseData, UpdateCaseData> {
  getTimeline(caseId: string): Promise<ApiResponse<TimelineEntry[]>>;
  addTimelineEntry(caseId: string, entry: Omit<TimelineEntry, 'id' | 'ts'>): Promise<ApiResponse<TimelineEntry>>;
}

// Task service interface
export interface CreateTaskData {
  title: string;
  description: string;
  caseId: string;
  stage: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  assignedToId: string;
  assignedToName: string;
  assignedById: string;
  assignedByName: string;
  dueDate: string;
  estimatedHours: number;
  isAutoGenerated?: boolean;
  bundleId?: string;
}

export interface UpdateTaskData extends Partial<CreateTaskData> {
  status?: 'Not Started' | 'In Progress' | 'Review' | 'Completed' | 'Overdue';
  completedDate?: string;
  actualHours?: number;
}

export interface TaskService extends CrudService<Task, CreateTaskData, UpdateTaskData> {
  getByCase(caseId: string): Promise<ApiResponse<Task[]>>;
  getByAssignee(assigneeId: string): Promise<ApiResponse<Task[]>>;
  bulkCreate(tasks: CreateTaskData[]): Promise<ApiResponse<Task[]>>;
}

// Court service interface
export interface CreateCourtData {
  name: string;
  type: 'Supreme Court' | 'High Court' | 'District Court' | 'Tribunal' | 'Commission';
  jurisdiction: string;
  address: string;
  establishedYear: number;
  digitalFiling: boolean;
  workingDays: string[];
  phone?: string;
  email?: string;
  benchLocation?: string;
}

export interface UpdateCourtData extends Partial<CreateCourtData> {}

export interface CourtService extends CrudService<Court, CreateCourtData, UpdateCourtData> {}

// Judge service interface
export interface CreateJudgeData {
  name: string;
  designation: string;
  status: 'Active' | 'On Leave' | 'Retired' | 'Transferred' | 'Deceased';
  courtId: string;
  appointmentDate: string;
  specialization: string[];
  retirementDate?: string;
  bench?: string;
  jurisdiction?: string;
  city?: string;
  state?: string;
  email?: string;
  phone?: string;
}

export interface UpdateJudgeData extends Partial<CreateJudgeData> {}

export interface JudgeService extends CrudService<Judge, CreateJudgeData, UpdateJudgeData> {
  getByCourt(courtId: string): Promise<ApiResponse<Judge[]>>;
}

// Employee service interface
export interface CreateEmployeeData {
  full_name: string;
  role: 'Partner' | 'CA' | 'Advocate' | 'Staff' | 'RM' | 'Finance' | 'Admin';
  email: string;
  mobile?: string;
  status: 'Active' | 'Inactive';
  date_of_joining?: string;
  notes?: string;
  department: string;
  workloadCapacity: number;
  specialization?: string[];
}

export interface UpdateEmployeeData extends Partial<CreateEmployeeData> {}

export interface EmployeeService extends CrudService<Employee, CreateEmployeeData, UpdateEmployeeData> {}

// Hearing service interface
export interface CreateHearingData {
  case_id: string;
  date: string;
  start_time: string;
  end_time: string;
  court_id: string;
  judge_ids: string[];
  purpose: 'PH' | 'mention' | 'final' | 'other';
  courtroom?: string;
  notes?: string;
  created_by: string;
}

export interface UpdateHearingData extends Partial<CreateHearingData> {
  status?: 'scheduled' | 'concluded' | 'adjourned' | 'no-board' | 'withdrawn';
  outcome?: string;
  outcome_text?: string;
  next_hearing_date?: string;
}

export interface HearingService extends CrudService<Hearing, CreateHearingData, UpdateHearingData> {
  getByCase(caseId: string): Promise<ApiResponse<Hearing[]>>;
  getByDateRange(startDate: string, endDate: string): Promise<ApiResponse<Hearing[]>>;
}

// Document service interface
export interface CreateDocumentData {
  name: string;
  type: string;
  size: number;
  caseId: string;
  uploadedById: string;
  uploadedByName: string;
  tags: string[];
  isShared: boolean;
  path: string;
  content?: string;
  folderId?: string;
}

export interface UpdateDocumentData extends Partial<CreateDocumentData> {}

export interface DocumentService extends CrudService<Document, CreateDocumentData, UpdateDocumentData> {
  getByCase(caseId: string): Promise<ApiResponse<Document[]>>;
  getByFolder(folderId: string): Promise<ApiResponse<Document[]>>;
  bulkUpload(documents: CreateDocumentData[]): Promise<ApiResponse<Document[]>>;
}

// Task Bundle service interface
export interface CreateTaskBundleData {
  name: string;
  description: string;
  stageKey: string;
  triggerType: 'manual' | 'stage_entry' | 'stage_exit' | 'time_based';
  isActive: boolean;
  tasks: Omit<TaskTemplate, 'id'>[];
}

export interface UpdateTaskBundleData extends Partial<CreateTaskBundleData> {}

export interface TaskBundleService extends CrudService<TaskBundle, CreateTaskBundleData, UpdateTaskBundleData> {
  execute(bundleId: string, caseId: string, stageKey: string): Promise<ApiResponse<Task[]>>;
  getByStage(stageKey: string): Promise<ApiResponse<TaskBundle[]>>;
}

// Import/Export interfaces
export interface ImportOptions {
  conflictPolicy: 'skip' | 'merge' | 'create_new';
  validateOnly?: boolean;
}

export interface ImportResult {
  success: boolean;
  imported: number;
  skipped: number;
  errors: string[];
  warnings: string[];
}

export interface ExportOptions {
  format: 'csv' | 'json';
  includeHeaders?: boolean;
  selectedFields?: string[];
}

export interface ImportExportService {
  import<T>(entity: string, data: any[], options: ImportOptions): Promise<ApiResponse<ImportResult>>;
  export<T>(entity: string, data: T[], options: ExportOptions): Promise<ApiResponse<string>>;
  validateImport(entity: string, data: any[]): Promise<ApiResponse<{ valid: boolean; errors: string[] }>>;
}

// Error types
export enum ApiErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  STORAGE_ERROR = 'STORAGE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR'
}

export interface ApiError {
  code: ApiErrorCode;
  message: string;
  details?: any;
}

// Utility types for service responses
export type ServiceResult<T> = Promise<ApiResponse<T>>;
export type ServiceListResult<T> = Promise<ApiResponse<T[]>>;