import React, { createContext, useContext, useReducer, ReactNode } from 'react';

// Types
interface Case {
  id: string;
  caseNumber: string;
  title: string;
  clientId: string; // FK to Client.id
  currentStage: 'Scrutiny' | 'Demand' | 'Adjudication' | 'Appeals' | 'GSTAT' | 'HC' | 'SC';
  priority: 'High' | 'Medium' | 'Low';
  slaStatus: 'Green' | 'Amber' | 'Red';
  nextHearing?: {
    date: string;
    courtId: string; // FK to Court.id
    judgeId: string; // FK to Judge.id
    type: 'Adjourned' | 'Final' | 'Argued';
  };
  assignedToId: string; // FK to Employee.id
  assignedToName: string; // Display name derived from Employee
  createdDate: string;
  lastUpdated: string;
  documents: number;
  progress: number;
}

interface Task {
  id: string;
  title: string;
  description: string;
  caseId: string; // FK to Case.id (required)
  clientId: string; // Derived from Case.clientId (auto-populated, read-only)
  caseNumber: string; // Derived from Case.caseNumber (auto-populated)
  stage: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  status: 'Not Started' | 'In Progress' | 'Review' | 'Completed' | 'Overdue';
  assignedToId: string; // FK to Employee.id
  assignedToName: string; // Display name derived from Employee
  assignedById: string; // FK to Employee.id
  assignedByName: string; // Display name derived from Employee
  createdDate: string;
  dueDate: string;
  completedDate?: string;
  estimatedHours: number;
  actualHours?: number;
  isAutoGenerated: boolean;
  bundleId?: string;
  dependencies?: string[];
  attachments?: string[];
  escalationLevel: 0 | 1 | 2 | 3;
}

interface Client {
  id: string;
  name: string;
  type: 'Individual' | 'Company' | 'Partnership' | 'Trust' | 'Society';
  email: string;
  phone: string;
  address: string;
  registrationNumber?: string;
  panNumber: string;
  gstNumber?: string;
  status: 'Active' | 'Inactive';
  assignedCAId: string; // FK to Employee.id  
  assignedCAName: string; // Display name derived from Employee
  registrationDate: string;
  totalCases: number;
  activeCases: number;
  totalInvoiced: number;
}

interface Court {
  id: string;
  name: string;
  type: 'Supreme Court' | 'High Court' | 'District Court' | 'Tribunal' | 'Commission';
  jurisdiction: string;
  address: string;
  establishedYear: number;
  totalJudges: number;
  activeCases: number;
  avgHearingTime: string;
  digitalFiling: boolean;
  workingDays: string[];
}

interface Judge {
  id: string;
  name: string;
  designation: string;
  courtId: string; // FK to Court.id
  appointmentDate: string;
  specialization: string[];
  totalCases: number;
  avgDisposalTime: string;
  retirementDate: string;
  status: 'Active' | 'On Leave' | 'Retired';
  contactInfo: {
    chambers: string;
    phone?: string;
    email?: string;
  };
}

interface Document {
  id: string;
  name: string;
  type: string;
  size: number;
  caseId: string; // FK to Case.id (required)
  clientId: string; // Derived from Case.clientId (auto-populated)
  uploadedById: string; // FK to Employee.id
  uploadedByName: string; // Display name derived from Employee
  uploadedAt: string;
  tags: string[];
  isShared: boolean;
  path: string;
}

// Employee interface for universal assignment system
interface Employee {
  id: string;
  name: string;
  role: 'Partner' | 'Associate' | 'Paralegal' | 'Admin' | 'CA' | 'Manager' | 'Senior Associate';
  email: string;
  status: 'Active' | 'On Leave' | 'Inactive';
  department: string;
  joiningDate: string;
  workloadCapacity: number;
  phone?: string;
  specialization?: string[];
}

// New interface for Hearing entity
interface Hearing {
  id: string;
  caseId: string; // FK to Case.id
  clientId: string; // Derived from Case.clientId
  courtId: string; // FK to Court.id
  judgeId: string; // FK to Judge.id
  date: string;
  time: string;
  type: 'Adjourned' | 'Final' | 'Argued' | 'Preliminary';
  status: 'Scheduled' | 'Completed' | 'Postponed' | 'Cancelled';
  agenda: string;
  notes?: string;
  createdDate: string;
  lastUpdated: string;
}

// Application State
export interface AppState {
  cases: Case[];
  tasks: Task[];
  clients: Client[];
  courts: Court[];
  judges: Judge[];
  documents: Document[];
  hearings: Hearing[];
  employees: Employee[];
  isLoading: boolean;
  error: string | null;
}

// Actions
export type AppAction =
  | { type: 'SET_LOADING'; payload: boolean }
  | { type: 'SET_ERROR'; payload: string | null }
  | { type: 'ADD_CASE'; payload: Case }
  | { type: 'UPDATE_CASE'; payload: Partial<Case> & { id: string } }
  | { type: 'DELETE_CASE'; payload: string }
  | { type: 'ADD_TASK'; payload: Task }
  | { type: 'UPDATE_TASK'; payload: Task }
  | { type: 'DELETE_TASK'; payload: string }
  | { type: 'ADD_CLIENT'; payload: Client }
  | { type: 'UPDATE_CLIENT'; payload: Client }
  | { type: 'DELETE_CLIENT'; payload: string }
  | { type: 'ADD_COURT'; payload: Court }
  | { type: 'UPDATE_COURT'; payload: Court }
  | { type: 'DELETE_COURT'; payload: string }
  | { type: 'ADD_JUDGE'; payload: Judge }
  | { type: 'UPDATE_JUDGE'; payload: Judge }
  | { type: 'DELETE_JUDGE'; payload: string }
  | { type: 'ADD_DOCUMENT'; payload: Document }
  | { type: 'UPDATE_DOCUMENT'; payload: Document }
  | { type: 'DELETE_DOCUMENT'; payload: string }
  | { type: 'ADD_HEARING'; payload: Hearing }
  | { type: 'UPDATE_HEARING'; payload: Partial<Hearing> & { id: string } }
  | { type: 'DELETE_HEARING'; payload: string }
  | { type: 'ADD_EMPLOYEE'; payload: Employee }
  | { type: 'UPDATE_EMPLOYEE'; payload: Employee }
  | { type: 'DELETE_EMPLOYEE'; payload: string }
  | { type: 'RESTORE_STATE'; payload: Partial<AppState> }
  | { type: 'CLEAR_ALL_DATA' };

// Initial state with mock data
const initialState: AppState = {
  cases: [
    {
      id: '1',
      caseNumber: 'CASE-2024-001',
      title: 'Tax Assessment Appeal - Acme Corp',
      clientId: '1', // FK to Acme Corporation Ltd
      currentStage: 'Adjudication',
      priority: 'High',
      slaStatus: 'Red',
      nextHearing: {
        date: '2024-02-15',
        courtId: '1', // FK to Income Tax Appellate Tribunal
        judgeId: '1', // FK to Justice Rajesh Sharma
        type: 'Final'
      },
      assignedToId: '1',
      assignedToName: 'John Smith',
      createdDate: '2024-01-10',
      lastUpdated: '2024-01-20',
      documents: 15,
      progress: 65
    },
    {
      id: '2',
      caseNumber: 'CASE-2024-002',
      title: 'GST Demand Notice Challenge',
      clientId: '2', // FK to Global Tech Solutions (need to add this client)
      currentStage: 'Demand',
      priority: 'Medium',
      slaStatus: 'Amber',
      assignedToId: '2',
      assignedToName: 'Sarah Johnson',
      createdDate: '2024-01-15',
      lastUpdated: '2024-01-22',
      documents: 8,
      progress: 40
    }
  ],
  tasks: [
    {
      id: '1',
      title: 'Draft Response to DRC-01 Notice',
      description: 'Prepare comprehensive response addressing all points raised in the demand notice',
      caseId: '1',
      clientId: '1', // Auto-derived from Case.clientId
      caseNumber: 'CASE-2024-001', // Auto-derived from Case.caseNumber
      stage: 'Demand',
      priority: 'Critical',
      status: 'Overdue',
      assignedToId: '1',
      assignedToName: 'John Smith',
      assignedById: '3',
      assignedByName: 'Mike Wilson',
      createdDate: '2024-01-15',
      dueDate: '2024-01-20',
      estimatedHours: 16,
      actualHours: 20,
      isAutoGenerated: true,
      bundleId: 'demand-response-bundle',
      escalationLevel: 2
    }
  ],
  clients: [
    {
      id: '1',
      name: 'Acme Corporation Ltd',
      type: 'Company',
      email: 'contact@acme.com',
      phone: '+91-9876543210',
      address: '123 Business Park, Mumbai',
      registrationNumber: 'U12345MH2020PLC123456',
      panNumber: 'ABCDE1234F',
      gstNumber: '27ABCDE1234F1Z5',
      status: 'Active',
      assignedCAId: '1',
      assignedCAName: 'John Smith',
      registrationDate: '2024-01-15',
      totalCases: 5,
      activeCases: 2,
      totalInvoiced: 250000
    },
    {
      id: '2',
      name: 'Global Tech Solutions',
      type: 'Company',
      email: 'info@globaltech.com',
      phone: '+91-9876543211',
      address: '456 Tech Plaza, Bangalore',
      registrationNumber: 'U12346KA2021PLC123457',
      panNumber: 'ABCDE1235G',
      gstNumber: '29ABCDE1235G1Z6',
      status: 'Active',
      assignedCAId: '2',
      assignedCAName: 'Sarah Johnson',
      registrationDate: '2024-01-10',
      totalCases: 3,
      activeCases: 1,
      totalInvoiced: 180000
    }
  ],
  courts: [
    {
      id: '1',
      name: 'Income Tax Appellate Tribunal',
      type: 'Tribunal',
      jurisdiction: 'Mumbai',
      address: 'Aayakar Bhavan, M.K. Road, Mumbai',
      establishedYear: 1941,
      totalJudges: 15,
      activeCases: 450,
      avgHearingTime: '45 mins',
      digitalFiling: true,
      workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
    }
  ],
  judges: [
    {
      id: '1',
      name: 'Justice Rajesh Sharma',
      designation: 'Chief Justice',
      courtId: '1', // FK to Income Tax Appellate Tribunal
      appointmentDate: '2015-06-15',
      specialization: ['Tax Law', 'Corporate Law'],
      totalCases: 1250,
      avgDisposalTime: '8 months',
      retirementDate: '2030-06-14',
      status: 'Active',
      contactInfo: {
        chambers: 'Chamber No. 15, ITAT Mumbai',
        phone: '+91-22-12345678',
        email: 'justice.sharma@itat.gov.in'
      }
    }
  ],
  documents: [
    {
      id: '1',
      name: 'DRC-01 Notice.pdf',
      type: 'pdf',
      size: 1024000,
      caseId: '1',
      clientId: '1', // Auto-derived from Case.clientId
      uploadedById: '1',
      uploadedByName: 'John Smith',
      uploadedAt: '2024-01-15T10:30:00Z',
      tags: ['Notice', 'DRC-01', 'Important'],
      isShared: false,
      path: '/documents/case-1/drc-01-notice.pdf'
    }
  ],
  hearings: [
    {
      id: '1',
      caseId: '1',
      clientId: '1', // Auto-derived from Case.clientId
      courtId: '1',
      judgeId: '1',
      date: '2024-02-15',
      time: '10:30',
      type: 'Final',
      status: 'Scheduled',
      agenda: 'Final arguments for tax assessment appeal',
      createdDate: '2024-01-10',
      lastUpdated: '2024-01-20'
    }
  ],
  employees: [
    {
      id: '1',
      name: 'John Smith',
      role: 'Partner',
      email: 'john.smith@lawfirm.com',
      status: 'Active',
      department: 'Corporate Law',
      joiningDate: '2018-03-15',
      workloadCapacity: 40,
      phone: '+91-9876543210',
      specialization: ['Corporate Law', 'Tax Law', 'Mergers & Acquisitions']
    },
    {
      id: '2',
      name: 'Sarah Johnson',
      role: 'Senior Associate',
      email: 'sarah.johnson@lawfirm.com',
      status: 'Active',
      department: 'Tax Law',
      joiningDate: '2020-08-01',
      workloadCapacity: 35,
      phone: '+91-9876543211',
      specialization: ['Tax Law', 'GST', 'Income Tax Appeals']
    },
    {
      id: '3',
      name: 'Mike Wilson',
      role: 'Manager',
      email: 'mike.wilson@lawfirm.com',
      status: 'Active',
      department: 'Operations',
      joiningDate: '2017-01-10',
      workloadCapacity: 30,
      phone: '+91-9876543212',
      specialization: ['Team Management', 'Operations', 'Client Relations']
    },
    {
      id: '4',
      name: 'Emily Chen',
      role: 'Associate',
      email: 'emily.chen@lawfirm.com',
      status: 'Active',
      department: 'Litigation',
      joiningDate: '2022-06-15',
      workloadCapacity: 25,
      phone: '+91-9876543213',
      specialization: ['Litigation', 'Civil Law', 'Commercial Disputes']
    },
    {
      id: '5',
      name: 'David Kumar',
      role: 'CA',
      email: 'david.kumar@lawfirm.com',
      status: 'Active',
      department: 'Tax Law',
      joiningDate: '2019-11-20',
      workloadCapacity: 30,
      phone: '+91-9876543214',
      specialization: ['Chartered Accountancy', 'Tax Planning', 'Audit']
    },
    {
      id: '6',
      name: 'Lisa Patel',
      role: 'Paralegal',
      email: 'lisa.patel@lawfirm.com',
      status: 'On Leave',
      department: 'Support',
      joiningDate: '2021-02-12',
      workloadCapacity: 20,
      phone: '+91-9876543215',
      specialization: ['Research', 'Documentation', 'Case Management']
    }
  ],
  isLoading: false,
  error: null
};

// Reducer
function appReducer(state: AppState, action: AppAction): AppState {
  switch (action.type) {
    case 'SET_LOADING':
      return { ...state, isLoading: action.payload };
    case 'SET_ERROR':
      return { ...state, error: action.payload };
    case 'ADD_CASE':
      return { ...state, cases: [...state.cases, action.payload] };
    case 'UPDATE_CASE':
      return {
        ...state,
        cases: state.cases.map(c => c.id === action.payload.id ? { ...c, ...action.payload } : c)
      };
    case 'DELETE_CASE':
      return {
        ...state,
        cases: state.cases.filter(c => c.id !== action.payload)
      };
    case 'ADD_TASK':
      return { ...state, tasks: [...state.tasks, action.payload] };
    case 'UPDATE_TASK':
      return {
        ...state,
        tasks: state.tasks.map(t => t.id === action.payload.id ? action.payload : t)
      };
    case 'DELETE_TASK':
      return {
        ...state,
        tasks: state.tasks.filter(t => t.id !== action.payload)
      };
    case 'ADD_CLIENT':
      return { ...state, clients: [...state.clients, action.payload] };
    case 'UPDATE_CLIENT':
      return {
        ...state,
        clients: state.clients.map(c => c.id === action.payload.id ? action.payload : c)
      };
    case 'DELETE_CLIENT':
      return {
        ...state,
        clients: state.clients.filter(c => c.id !== action.payload)
      };
    case 'ADD_COURT':
      return { ...state, courts: [...state.courts, action.payload] };
    case 'UPDATE_COURT':
      return {
        ...state,
        courts: state.courts.map(c => c.id === action.payload.id ? action.payload : c)
      };
    case 'DELETE_COURT':
      return {
        ...state,
        courts: state.courts.filter(c => c.id !== action.payload)
      };
    case 'ADD_JUDGE':
      return { ...state, judges: [...state.judges, action.payload] };
    case 'UPDATE_JUDGE':
      return {
        ...state,
        judges: state.judges.map(j => j.id === action.payload.id ? action.payload : j)
      };
    case 'DELETE_JUDGE':
      return {
        ...state,
        judges: state.judges.filter(j => j.id !== action.payload)
      };
    case 'ADD_DOCUMENT':
      return { ...state, documents: [...state.documents, action.payload] };
    case 'UPDATE_DOCUMENT':
      return {
        ...state,
        documents: state.documents.map(d => d.id === action.payload.id ? action.payload : d)
      };
    case 'DELETE_DOCUMENT':
      return {
        ...state,
        documents: state.documents.filter(d => d.id !== action.payload)
      };
    case 'ADD_HEARING':
      return { ...state, hearings: [...state.hearings, action.payload] };
    case 'UPDATE_HEARING':
      return {
        ...state,
        hearings: state.hearings.map(h => h.id === action.payload.id ? { ...h, ...action.payload } : h)
      };
    case 'DELETE_HEARING':
      return {
        ...state,
        hearings: state.hearings.filter(h => h.id !== action.payload)
      };
    case 'ADD_EMPLOYEE':
      return { ...state, employees: [...state.employees, action.payload] };
    case 'UPDATE_EMPLOYEE':
      return {
        ...state,
        employees: state.employees.map(e => e.id === action.payload.id ? action.payload : e)
      };
    case 'DELETE_EMPLOYEE':
      return {
        ...state,
        employees: state.employees.filter(e => e.id !== action.payload)
      };
    case 'RESTORE_STATE':
      return { ...state, ...action.payload };
    case 'CLEAR_ALL_DATA':
      return {
        ...initialState,
        cases: [],
        tasks: [],
        clients: [],
        courts: [],
        judges: [],
        documents: [],
        hearings: [],
        employees: [],
      };
    default:
      return state;
  }
}

// Context
const AppStateContext = createContext<{
  state: AppState;
  dispatch: React.Dispatch<AppAction>;
} | null>(null);

// Provider
export const AppStateProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [state, dispatch] = useReducer(appReducer, initialState);

  return (
    <AppStateContext.Provider value={{ state, dispatch }}>
      {children}
    </AppStateContext.Provider>
  );
};

// Hook
export const useAppState = () => {
  const context = useContext(AppStateContext);
  if (!context) {
    throw new Error('useAppState must be used within AppStateProvider');
  }
  return context;
};

// Export types
export type { Case, Task, Client, Court, Judge, Document, Hearing, Employee };