import React, { createContext, useContext, useReducer, ReactNode, useEffect } from 'react';
import { calendarSyncService } from '@/services/calendar/calendarSyncService';

// Types
interface GeneratedForm {
  formCode: string;
  version: number;
  generatedDate: string;
  employeeId: string;
  employeeName: string;
  documentId?: string;
  fileName: string;
  status: 'Generated' | 'Uploaded';
}

interface Case {
  id: string;
  caseNumber: string;
  title: string;
  clientId: string; // FK to Client.id
  currentStage: 'Assessment' | 'Adjudication' | 'First Appeal' | 'Tribunal' | 'High Court' | 'Supreme Court';
  priority: 'High' | 'Medium' | 'Low';
  timelineBreachStatus: 'Green' | 'Amber' | 'Red';
  status?: 'Active' | 'Completed';
  completedDate?: string;
  reviewDate?: string;
  nextHearing?: {
    date: string;
    courtId: string; // FK to Court.id
    judgeId: string; // FK to Judge.id
    type: 'Adjourned' | 'Final' | 'Argued';
  };
  assignedToId: string; // FK to Employee.id
  assignedToName: string; // Display name derived from Employee
  createdDate: string;
  lastUpdated: string;
  documents: number;
  progress: number;
  generatedForms: GeneratedForm[]; // Track completed forms
  amountInDispute?: number; // Amount in dispute for GST cases
  description?: string; // Case description
  
  // NEW FIELDS - Client Request Updates
  caseType?: 'GST' | 'ST' | 'Excise' | 'Custom' | 'VAT' | 'DGFT'; // Case type taxonomy
  issueType?: string; // Issue/matter name (used with client name for title)
  caseYear?: string; // Year component of case number
  caseSequence?: string; // Sequence number within year
  officeFileNo?: string; // Office file reference number
  noticeNo?: string; // Notice reference number
  period?: string; // Tax period (e.g., "Q1 FY2024-25")
  taxDemand?: number; // Tax amount in dispute
  authority?: string; // Issuing authority name
  jurisdictionalCommissionerate?: string; // Jurisdictional office
  departmentLocation?: string; // Department location
  matterType?: 'Scrutiny' | 'General Inquiry' | 'Audit' | 'Investigation' | 'Refund' | 'Advance Ruling' | 'Amnesty' | 'E-waybill'; // Matter type for Assessment stage
  tribunalBench?: 'State Bench' | 'Principal Bench'; // Tribunal bench selection for routing
  
  // Backward compatibility
  slaStatus?: 'Green' | 'Amber' | 'Red'; // Deprecated: use timelineBreachStatus
}

interface Task {
  id: string;
  title: string;
  description: string;
  caseId: string; // FK to Case.id (required)
  clientId: string; // Derived from Case.clientId (auto-populated, read-only)
  caseNumber: string; // Derived from Case.caseNumber (auto-populated)
  stage: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  status: 'Not Started' | 'In Progress' | 'Review' | 'Completed' | 'Overdue';
  assignedToId: string; // FK to Employee.id
  assignedToName: string; // Display name derived from Employee
  assignedById: string; // FK to Employee.id
  assignedByName: string; // Display name derived from Employee
  createdDate: string;
  dueDate: string;
  completedDate?: string;
  estimatedHours: number;
  actualHours?: number;
  isAutoGenerated: boolean;
  bundleId?: string;
  dependencies?: string[];
  attachments?: string[];
  escalationLevel: 0 | 1 | 2 | 3;
  followUpDate?: string; // Next follow-up date
}

// Task Note/Activity interface
export interface TaskNote {
  id: string;
  taskId: string;
  type: 'comment' | 'status_change' | 'time_log' | 'follow_up';
  note: string;
  createdBy: string;
  createdByName: string;
  createdAt: string;
  metadata?: {
    oldStatus?: string;
    newStatus?: string;
    hours?: number;
    followUpDate?: string;
  };
}

interface ClientGroup {
  id: string;
  name: string;
  description?: string;
  clients: string[]; // Array of Client IDs
  createdDate: string;
  lastUpdated: string;
}

interface Address {
  street: string;
  city: string;
  state: string;
  zip: string;
  country: string;
}

interface Jurisdiction {
  name: string;
  type: 'State' | 'Federal' | 'International';
}

interface PortalAccess {
  username?: string;
  password?: string;
  lastLogin?: string;
  status: 'Active' | 'Inactive' | 'Pending';
}

interface Signatory {
  name: string;
  designation: string;
  email?: string;
  phone?: string;
  signature?: string; // URL or base64 data
}

interface Client {
  id: string;
  name: string;
  email: string;
  phone: string;
  address: Address;
  jurisdiction: Jurisdiction;
  cases: number;
  openTasks: number;
  documents: number;
  portalAccess: PortalAccess;
  signatories: Signatory[];
  clientGroup?: string; // FK to ClientGroup.id
  notes?: string;
  matterType?: string;
  gstin?: string;
  pan?: string;
  cin?: string;
  iec?: string;
  contactPerson?: string;
  incorporationDate?: string;
  registeredAddress?: Address;
  billingAddress?: Address;
  shippingAddress?: Address;
  authorizedSignatory?: Signatory;
  authorizedRepresentative?: Signatory;
  complianceStatus?: string;
  riskScore?: number;
  tags?: string[];
  // Legacy support
  slaStatus?: 'Green' | 'Amber' | 'Red'; // Deprecated: use timelineBreachStatus
}

export interface Court {
  id: string;
  name: string;
  type: 'Supreme Court' | 'High Court' | 'District Court' | 'Tribunal' | 'Commission';
  jurisdiction: string;
  address: string;
  activeCases: number;
  avgHearingTime: string;
  digitalFiling: boolean;
  workingDays: string[];
  phone?: string;
  email?: string;
  benchLocation?: string;
}

export type Forum = Court;

interface Judge {
  id: string;
  name: string;
  designation: string;
  status: 'Active' | 'On Leave' | 'Retired' | 'Transferred' | 'Deceased';
  courtId: string; // FK to Court.id
  bench?: string;
  jurisdiction?: string;
  city?: string;
  state?: string;
  appointmentDate: string;
  retirementDate?: string;
  yearsOfService: number;
  specialization: string[];
  chambers?: string;
  email?: string;
  phone?: string;
  assistant?: {
    name?: string;
    email?: string;
    phone?: string;
  };
  address?: any;
  availability?: {
    days?: ('Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat')[];
    startTime?: string;
    endTime?: string;
    notes?: string;
  };
  tags?: string[];
  notes?: string;
  totalCases: number;
  avgDisposalTime: string;
  contactInfo?: {
    chambers: string;
    phone?: string;
    email?: string;
  };
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}

interface Employee {
  id: string;
  name: string;
  email: string;
  phone: string;
  designation: string;
  department: string;
  roles: ('Admin' | 'Manager' | 'Associate' | 'Paralegal')[];
  address: Address;
  joiningDate: string;
  leavingDate?: string;
  salary: number;
  bio?: string;
  avatar?: string;
  status: 'Active' | 'Inactive' | 'On Leave';
  permissions: string[];
  performanceScore: number;
  reportingManagerId?: string; // FK to Employee.id
  subordinates?: string[]; // Array of Employee IDs
  documents: number;
  tasks: number;
  leaves: number;
  location?: string;
  timezone?: string;
  notes?: string;
  // Legacy support
  level?: string; // Deprecated: use designation
}

interface Hearing {
  id: string;
  caseId: string; // FK to Case.id
  courtId: string; // FK to Court.id
  judgeId: string; // FK to Judge.id
  date: string;
  time: string;
  type: 'Adjourned' | 'Final' | 'Argued';
  status: 'Scheduled' | 'In Progress' | 'Completed' | 'Postponed' | 'Cancelled';
  notes?: string;
  documents: string[];
  attendees: string[]; // Array of Employee IDs
  outcome?: string;
  nextHearingDate?: string;
  nextSteps?: string;
  court_id?: string; // Legacy court id
  case_id?: string; // Legacy case id
}

interface Document {
  id: string;
  caseId: string; // FK to Case.id
  clientId: string; // FK to Client.id
  title: string;
  description?: string;
  type: 'Petition' | 'Evidence' | 'Order' | 'Judgment' | 'Correspondence' | 'Other';
  status: 'Draft' | 'Final' | 'Filed' | 'Served';
  uploadedBy: string; // FK to Employee.id
  uploadedDate: string;
  lastUpdated: string;
  fileSize: string;
  fileType: string;
  fileName: string;
  url: string;
  folderId?: string; // FK to Folder.id
  tags?: string[];
  notes?: string;
}

interface Folder {
  id: string;
  name: string;
  description?: string;
  parentId?: string; // FK to Folder.id (for subfolders)
  createdBy: string; // FK to Employee.id
  createdDate: string;
  lastUpdated: string;
  documents: number;
  subfolders: number;
  path?: string; // Full path for breadcrumbs
  isShared: boolean;
  sharedWith?: string[]; // Array of Employee IDs
  tags?: string[];
  notes?: string;
}

// Timeline Entry interface
interface TimelineEntry {
  id: string;
  caseId: string; // FK to Case.id
  type: 'Case Created' | 'Task Created' | 'Hearing Scheduled' | 'Document Uploaded' | 'Status Change' | 'Note Added' | 'Other';
  date: string;
  description: string;
  employeeId?: string; // FK to Employee.id
  employeeName?: string;
  relatedItemId?: string; // ID of related item (e.g., Task.id, Document.id)
  metadata?: any; // Additional data (e.g., oldStatus, newStatus)
}

// AppState interface
export interface AppState {
  cases: Case[];
  clients: Client[];
  clientGroups: ClientGroup[];
  courts: Court[];
  judges: Judge[];
  employees: Employee[];
  hearings: Hearing[];
  tasks: Task[];
  taskNotes: TaskNote[];
  documents: Document[];
  folders: Folder[];
  timelineEntries: TimelineEntry[];
  tags: string[];
  userProfile: {
    id: string;
    name: string;
    email: string;
    phone: string;
    role: string;
    department: string;
    avatar: string;
    bio: string;
    location: string;
    timezone: string;
    joinedDate: string;
    lastLogin: string;
    isActive: boolean;
  };
  isLoading: boolean;
  error: null | string;
}

// Action Types
type ActionType =
  | { type: 'ADD_CASE'; payload: Case }
  | { type: 'UPDATE_CASE'; payload: Case }
  | { type: 'DELETE_CASE'; payload: string }
  | { type: 'ADD_CLIENT'; payload: Client }
  | { type: 'UPDATE_CLIENT'; payload: Client }
  | { type: 'DELETE_CLIENT'; payload: string }
  | { type: 'ADD_COURT'; payload: Court }
  | { type: 'UPDATE_COURT'; payload: Court }
  | { type: 'DELETE_COURT'; payload: string }
  | { type: 'ADD_JUDGE'; payload: Judge }
  | { type: 'UPDATE_JUDGE'; payload: Judge }
  | { type: 'DELETE_JUDGE'; payload: string }
  | { type: 'ADD_EMPLOYEE'; payload: Employee }
  | { type: 'UPDATE_EMPLOYEE'; payload: Employee }
  | { type: 'DELETE_EMPLOYEE'; payload: string }
  | { type: 'ADD_HEARING'; payload: Hearing }
  | { type: 'UPDATE_HEARING'; payload: Hearing }
  | { type: 'DELETE_HEARING'; payload: string }
  | { type: 'ADD_TASK'; payload: Task }
  | { type: 'UPDATE_TASK'; payload: Task }
  | { type: 'DELETE_TASK'; payload: string }
  | { type: 'ADD_TASK_NOTE'; payload: TaskNote }
  | { type: 'UPDATE_TASK_NOTE'; payload: TaskNote }
  | { type: 'DELETE_TASK_NOTE'; payload: string }
  | { type: 'ADD_DOCUMENT'; payload: Document }
  | { type: 'UPDATE_DOCUMENT'; payload: Document }
  | { type: 'DELETE_DOCUMENT'; payload: string }
  | { type: 'ADD_FOLDER'; payload: Folder }
  | { type: 'UPDATE_FOLDER'; payload: Folder }
  | { type: 'DELETE_FOLDER'; payload: string }
  | { type: 'ADD_TIMELINE_ENTRY'; payload: TimelineEntry }
  | { type: 'UPDATE_TIMELINE_ENTRY'; payload: TimelineEntry }
  | { type: 'DELETE_TIMELINE_ENTRY'; payload: string }
  | { type: 'SET_LOADING'; payload: boolean }
  | { type: 'SET_ERROR'; payload: string | null };

// Reducer Function
const reducer = (state: AppState, action: ActionType): AppState => {
  switch (action.type) {
    case 'ADD_CASE':
      return { ...state, cases: [...state.cases, action.payload] };
    case 'UPDATE_CASE':
      return {
        ...state,
        cases: state.cases.map(c => (c.id === action.payload.id ? action.payload : c)),
      };
    case 'DELETE_CASE':
      return { ...state, cases: state.cases.filter(c => c.id !== action.payload) };
    case 'ADD_CLIENT':
      return { ...state, clients: [...state.clients, action.payload] };
    case 'UPDATE_CLIENT':
      return {
        ...state,
        clients: state.clients.map(client =>
          client.id === action.payload.id ? action.payload : client
        ),
      };
    case 'DELETE_CLIENT':
      return { ...state, clients: state.clients.filter(client => client.id !== action.payload) };
    case 'ADD_COURT':
      return { ...state, courts: [...state.courts, action.payload] };
    case 'UPDATE_COURT':
      return {
        ...state,
        courts: state.courts.map(court => (court.id === action.payload.id ? action.payload : court)),
      };
    case 'DELETE_COURT':
      return { ...state, courts: state.courts.filter(court => court.id !== action.payload) };
    case 'ADD_JUDGE':
      return { ...state, judges: [...state.judges, action.payload] };
    case 'UPDATE_JUDGE':
      return {
        ...state,
        judges: state.judges.map(judge => (judge.id === action.payload.id ? action.payload : judge)),
      };
    case 'DELETE_JUDGE':
      return { ...state, judges: state.judges.filter(judge => judge.id !== action.payload) };
    case 'ADD_EMPLOYEE':
      return { ...state, employees: [...state.employees, action.payload] };
    case 'UPDATE_EMPLOYEE':
      return {
        ...state,
        employees: state.employees.map(employee =>
          employee.id === action.payload.id ? action.payload : employee
        ),
      };
    case 'DELETE_EMPLOYEE':
      return { ...state, employees: state.employees.filter(employee => employee.id !== action.payload) };
    case 'ADD_HEARING':
      return { ...state, hearings: [...state.hearings, action.payload] };
    case 'UPDATE_HEARING':
      return {
        ...state,
        hearings: state.hearings.map(hearing =>
          hearing.id === action.payload.id ? action.payload : hearing
        ),
      };
    case 'DELETE_HEARING':
      return { ...state, hearings: state.hearings.filter(hearing => hearing.id !== action.payload) };
    case 'ADD_TASK':
      return { ...state, tasks: [...state.tasks, action.payload] };
    case 'UPDATE_TASK':
      return {
        ...state,
        tasks: state.tasks.map(task => (task.id === action.payload.id ? action.payload : task)),
      };
    case 'DELETE_TASK':
      return { ...state, tasks: state.tasks.filter(task => task.id !== action.payload) };
    case 'ADD_TASK_NOTE':
      return { ...state, taskNotes: [...state.taskNotes, action.payload] };
    case 'UPDATE_TASK_NOTE':
      return {
        ...state,
        taskNotes: state.taskNotes.map(taskNote =>
          taskNote.id === action.payload.id ? action.payload : taskNote
        ),
      };
    case 'DELETE_TASK_NOTE':
      return { ...state, taskNotes: state.taskNotes.filter(taskNote => taskNote.id !== action.payload) };
    case 'ADD_DOCUMENT':
      return { ...state, documents: [...state.documents, action.payload] };
    case 'UPDATE_DOCUMENT':
      return {
        ...state,
        documents: state.documents.map(document =>
          document.id === action.payload.id ? action.payload : document
        ),
      };
    case 'DELETE_DOCUMENT':
      return { ...state, documents: state.documents.filter(document => document.id !== action.payload) };
    case 'ADD_FOLDER':
      return { ...state, folders: [...state.folders, action.payload] };
    case 'UPDATE_FOLDER':
      return {
        ...state,
        folders: state.folders.map(folder => (folder.id === action.payload.id ? action.payload : folder)),
      };
    case 'DELETE_FOLDER':
      return { ...state, folders: state.folders.filter(folder => folder.id !== action.payload) };
    case 'ADD_TIMELINE_ENTRY':
      return { ...state, timelineEntries: [...state.timelineEntries, action.payload] };
    case 'UPDATE_TIMELINE_ENTRY':
      return {
        ...state,
        timelineEntries: state.timelineEntries.map(timelineEntry =>
          timelineEntry.id === action.payload.id ? action.payload : timelineEntry
        ),
      };
    case 'DELETE_TIMELINE_ENTRY':
      return {
        ...state,
        timelineEntries: state.timelineEntries.filter(timelineEntry => timelineEntry.id !== action.payload),
      };
    case 'SET_LOADING':
      return { ...state, isLoading: action.payload };
    case 'SET_ERROR':
      return { ...state, error: action.payload };
    default:
      return state;
  }
};

// Initial State
const initialState: AppState = {
  cases: [],
  clients: [],
  clientGroups: [],
  courts: [],
  judges: [],
  employees: [],
  hearings: [],
  tasks: [],
  taskNotes: [],
  documents: [],
  folders: [],
  timelineEntries: [],
  tags: [],
  userProfile: {
    id: 'user-1',
    name: 'Default User',
    email: 'user@example.com',
    phone: '',
    role: 'Admin',
    department: 'Legal',
    avatar: '',
    bio: '',
    location: '',
    timezone: 'UTC',
    joinedDate: new Date().toISOString(),
    lastLogin: new Date().toISOString(),
    isActive: true,
  },
  isLoading: false,
  error: null,
};

// Context
interface AppContextProps {
  state: AppState;
  dispatch: React.Dispatch<ActionType>;
}

const AppContext = createContext<AppContextProps>({
  state: initialState,
  dispatch: () => null,
});

// Provider
interface AppProviderProps {
  children: ReactNode;
}

const AppProvider: React.FC<AppProviderProps> = ({ children }) => {
  const [state, dispatch] = useReducer(reducer, initialState);

  useEffect(() => {
    const syncCalendar = async () => {
      if (state.hearings && state.hearings.length > 0) {
        await calendarSyncService.syncEvents(state.hearings);
      }
    };

    syncCalendar();
  }, [state.hearings]);

  return <AppContext.Provider value={{ state, dispatch }}>{children}</AppContext.Provider>;
};

// Custom Hook
const useAppContext = () => useContext(AppContext);

export { AppProvider, useAppContext };
export type { ActionType };
