import React, { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogBody, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useAppState } from '@/contexts/AppStateContext';
import { useToast } from '@/hooks/use-toast';
import { AlertTriangle, Plus, Clock, User } from 'lucide-react';
import { FieldTooltip } from '@/components/ui/field-tooltip';

interface ActionItemModalProps {
  isOpen: boolean;
  onClose: () => void;
  caseId: string | null;
  urgencyLevel: 'High' | 'Medium' | 'Low';
  suggestedAction?: string;
}

export const ActionItemModal: React.FC<ActionItemModalProps> = ({
  isOpen,
  onClose,
  caseId,
  urgencyLevel,
  suggestedAction = ''
}) => {
  const { state, dispatch } = useAppState();
  const { toast } = useToast();
  const [formData, setFormData] = useState({
    title: suggestedAction,
    description: '',
    priority: urgencyLevel,
    assignee: '',
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0] // Tomorrow
  });

  const availableAssignees = [
    'Partner 1',
    'Associate 1', 
    'Associate 2',
    'Paralegal 1',
    'Paralegal 2'
  ];

  const handleCreateTask = () => {
    if (!caseId || !formData.title || !formData.assignee) {
      toast({
        title: "Missing Information",
        description: "Please fill in all required fields",
        variant: "destructive"
      });
      return;
    }

    const caseData = state.cases.find(c => c.id === caseId);
    if (!caseData) return;

    dispatch({
      type: 'ADD_TASK',
      payload: {
        id: `task-${Date.now()}`,
        title: formData.title,
        description: formData.description,
        priority: formData.priority as 'High' | 'Medium' | 'Low',
        status: 'Not Started' as const,
        dueDate: new Date(formData.dueDate).toISOString(),
        assignedToId: formData.assignee,
        assignedToName: state.employees.find(e => e.id === formData.assignee)?.full_name || '',
        caseId: caseId,
        clientId: caseData.clientId,
        createdDate: new Date().toISOString(),
        caseNumber: caseData.caseNumber,
        stage: 'Planning',
        assignedById: '3',
        assignedByName: 'System',
        estimatedHours: 2,
        actualHours: 0,
        isAutoGenerated: false,
        escalationLevel: 0
      }
    });

    toast({
      title: "Action Item Created",
      description: `Task assigned to ${formData.assignee}`,
    });

    onClose();
    setFormData({
      title: '',
      description: '',
      priority: 'Medium',
      assignee: '',
      dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0]
    });
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-beacon-modal max-h-[90vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-warning" />
            Create Action Item
          </DialogTitle>
          <DialogDescription>
            Create a task to address the SLA breach
          </DialogDescription>
        </DialogHeader>

        <DialogBody className="space-y-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Urgency Level</CardTitle>
            </CardHeader>
            <CardContent>
              <Badge variant={
                urgencyLevel === 'High' ? 'destructive' : 
                urgencyLevel === 'Medium' ? 'default' : 
                'secondary'
              }>
                {urgencyLevel} Priority
              </Badge>
            </CardContent>
          </Card>

          <div className="space-y-2">
            <div className="flex items-center gap-1">
              <Label htmlFor="title">Task Title *</Label>
              <FieldTooltip formId="create-action-item" fieldId="title" />
            </div>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              placeholder="Enter task title..."
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center gap-1">
              <Label htmlFor="description">Description</Label>
              <FieldTooltip formId="create-action-item" fieldId="description" />
            </div>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Add task details..."
              rows={3}
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center gap-1">
              <Label htmlFor="assignee">Assign To *</Label>
              <FieldTooltip formId="create-action-item" fieldId="assignee" />
            </div>
            <Select value={formData.assignee} onValueChange={(value) => setFormData({ ...formData, assignee: value })}>
              <SelectTrigger>
                <SelectValue placeholder="Select assignee" />
              </SelectTrigger>
              <SelectContent>
                {availableAssignees.map((assignee) => (
                  <SelectItem key={assignee} value={assignee}>
                    <div className="flex items-center gap-2">
                      <User className="h-4 w-4" />
                      {assignee}
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="dueDate">Due Date *</Label>
            <Input
              id="dueDate"
              type="date"
              value={formData.dueDate}
              onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
            />
          </div>
        </DialogBody>

        <DialogFooter className="gap-3">
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button 
            onClick={handleCreateTask} 
            disabled={!formData.title || !formData.assignee}
          >
            <Plus className="mr-2 h-4 w-4" />
            Create Task
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};