import React, { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogBody, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useAppState } from '@/contexts/AppStateContext';
import { useToast } from '@/hooks/use-toast';
import { CheckSquare, FileText, User, Plus } from 'lucide-react';

interface ActionItemModalProps {
  isOpen: boolean;
  onClose: () => void;
  caseId: string | null;
  urgencyLevel: 'High' | 'Medium' | 'Low';
  suggestedAction?: string;
}

export const ActionItemModal: React.FC<ActionItemModalProps> = ({
  isOpen,
  onClose,
  caseId,
  urgencyLevel,
  suggestedAction = ''
}) => {
  const { state, dispatch } = useAppState();
  const { toast } = useToast();
  const [formData, setFormData] = useState({
    title: suggestedAction,
    description: '',
    priority: urgencyLevel,
    assignee: '',
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  });

  const availableAssignees = ['Partner 1', 'Associate 1', 'Associate 2', 'Paralegal 1', 'Paralegal 2'];

  const handleCreateTask = () => {
    if (!caseId || !formData.title || !formData.assignee) {
      toast({
        title: "Missing Information",
        description: "Please fill in all required fields",
        variant: "destructive"
      });
      return;
    }

    const caseData = state.cases.find(c => c.id === caseId);
    if (!caseData) return;

    const currentUserId = '3'; // TODO: Get from auth context
    
    dispatch({
      type: 'ADD_TASK',
      payload: {
        id: `task-${Date.now()}`,
        title: formData.title,
        description: formData.description,
        priority: formData.priority as 'High' | 'Medium' | 'Low',
        status: 'Not Started' as const,
        dueDate: new Date(formData.dueDate).toISOString(),
        assignedToId: formData.assignee,
        assignedToName: state.employees.find(e => e.id === formData.assignee)?.full_name || '',
        caseId: caseId,
        clientId: caseData.clientId,
        createdDate: new Date().toISOString(),
        caseNumber: caseData.caseNumber,
        stage: 'Planning',
        assignedById: currentUserId,
        assignedByName: 'System',
        estimatedHours: 2,
        actualHours: 0,
        isAutoGenerated: false,
        escalationLevel: 0,
        timezone: 'Asia/Kolkata',
        dueDateValidated: true,
        audit_trail: {
          created_by: currentUserId,
          created_at: new Date().toISOString(),
          updated_by: currentUserId,
          updated_at: new Date().toISOString(),
          change_log: []
        }
      }
    });

    toast({
      title: "Action Item Created",
      description: `Task assigned to ${formData.assignee}`,
    });

    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-beacon-modal max-h-[90vh]">
        <DialogHeader>
          <div className="flex items-center justify-between">
            <DialogTitle className="flex items-center gap-2">
              <CheckSquare className="h-5 w-5" />
              Create Action Item
            </DialogTitle>
            <Badge variant={urgencyLevel === 'High' ? 'destructive' : urgencyLevel === 'Medium' ? 'default' : 'secondary'}>
              {urgencyLevel}
            </Badge>
          </div>
        </DialogHeader>

        <DialogBody className="overflow-y-auto max-h-[60vh]">
          <form className="space-y-6">
            {/* Section 1: Task Information */}
            <div className="space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b">
                <FileText className="h-4 w-4 text-primary" />
                <h3 className="text-sm font-semibold">Task Information</h3>
              </div>
              <div>
                <Label htmlFor="title">Task Title <span className="text-destructive">*</span></Label>
                <Input
                  id="title"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  placeholder="Enter task title"
                  required
                />
              </div>
              <div>
                <Label htmlFor="description">Description</Label>
                <Textarea
                  id="description"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Enter task description"
                  rows={3}
                />
              </div>
            </div>

            {/* Section 2: Assignment & Schedule */}
            <div className="space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b">
                <User className="h-4 w-4 text-primary" />
                <h3 className="text-sm font-semibold">Assignment & Schedule</h3>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="assignee">Assign To <span className="text-destructive">*</span></Label>
                  <Select value={formData.assignee} onValueChange={(value) => setFormData({ ...formData, assignee: value })}>
                    <SelectTrigger id="assignee">
                      <SelectValue placeholder="Select assignee" />
                    </SelectTrigger>
                    <SelectContent>
                      {availableAssignees.map((assignee) => (
                        <SelectItem key={assignee} value={assignee}>
                          {assignee}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="dueDate">Due Date <span className="text-destructive">*</span></Label>
                  <Input
                    id="dueDate"
                    type="date"
                    value={formData.dueDate}
                    onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                    required
                  />
                </div>
              </div>
            </div>
          </form>
        </DialogBody>

        <DialogFooter className="gap-3">
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button onClick={handleCreateTask} disabled={!formData.title || !formData.assignee}>
            <Plus className="mr-2 h-4 w-4" />
            Create Task
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};