import React, { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useAppState } from '@/contexts/AppStateContext';
import { useToast } from '@/hooks/use-toast';
import { ArrowRight, Clock, AlertCircle, CheckCircle } from 'lucide-react';

interface StageManagementModalProps {
  isOpen: boolean;
  onClose: () => void;
  caseId: string | null;
  currentStage: string;
}

const stages = [
  'Scrutiny',
  'Demand', 
  'Adjudication',
  'Appeals',
  'GSTAT',
  'HC',
  'SC'
];

export const StageManagementModal: React.FC<StageManagementModalProps> = ({
  isOpen,
  onClose,
  caseId,
  currentStage
}) => {
  const { state, dispatch } = useAppState();
  const { toast } = useToast();
  const [selectedNextStage, setSelectedNextStage] = useState('');
  const [comments, setComments] = useState('');

  const currentStageIndex = stages.indexOf(currentStage);
  const availableNextStages = stages.slice(currentStageIndex + 1);

  const handleAdvanceStage = () => {
    if (!caseId || !selectedNextStage) return;

    const caseToUpdate = state.cases.find(c => c.id === caseId);
    if (!caseToUpdate) return;

    dispatch({
      type: 'UPDATE_CASE',
      payload: {
        ...caseToUpdate,
        currentStage: selectedNextStage as 'Scrutiny' | 'Demand' | 'Adjudication' | 'Appeals' | 'GSTAT' | 'HC' | 'SC'
      }
    });

    // Create audit task for stage advancement
    dispatch({
      type: 'ADD_TASK',
      payload: {
        id: `task-${Date.now()}`,
        title: `Stage Advanced: ${currentStage} → ${selectedNextStage}`,
        description: comments || `Case moved from ${currentStage} to ${selectedNextStage}`,
        priority: 'Medium' as const,
        status: 'Completed' as const,
        dueDate: new Date().toISOString(),
        assignedTo: 'System',
        caseId: caseId,
        clientId: state.cases.find(c => c.id === caseId)?.clientId || '',
        createdDate: new Date().toISOString(),
        caseNumber: caseToUpdate.caseNumber,
        stage: 'Audit',
        assignedBy: 'System',
        estimatedHours: 0,
        actualHours: 0,
        isAutoGenerated: true,
        escalationLevel: 0
      }
    });

    toast({
      title: "Stage Advanced",
      description: `Case moved from ${currentStage} to ${selectedNextStage}`,
    });

    onClose();
    setSelectedNextStage('');
    setComments('');
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Manage Case Stage</DialogTitle>
          <DialogDescription>
            Advance the case to the next stage in the lifecycle
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Current Stage</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-primary" />
                <Badge variant="secondary">{currentStage}</Badge>
              </div>
            </CardContent>
          </Card>

          <div className="space-y-2">
            <Label htmlFor="nextStage">Next Stage</Label>
            <Select value={selectedNextStage} onValueChange={setSelectedNextStage}>
              <SelectTrigger>
                <SelectValue placeholder="Select next stage" />
              </SelectTrigger>
              <SelectContent>
                {availableNextStages.map((stage) => (
                  <SelectItem key={stage} value={stage}>
                    <div className="flex items-center gap-2">
                      <ArrowRight className="h-4 w-4" />
                      {stage}
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="comments">Comments (Optional)</Label>
            <Textarea
              id="comments"
              placeholder="Add notes about this stage advancement..."
              value={comments}
              onChange={(e) => setComments(e.target.value)}
              rows={3}
            />
          </div>

          <div className="flex gap-2 pt-4">
            <Button variant="outline" onClick={onClose} className="flex-1">
              Cancel
            </Button>
            <Button 
              onClick={handleAdvanceStage} 
              disabled={!selectedNextStage}
              className="flex-1"
            >
              <CheckCircle className="mr-2 h-4 w-4" />
              Advance Stage
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};