import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { CalendarIcon } from 'lucide-react';
import { format } from 'date-fns';
import { toast } from '@/hooks/use-toast';
import { Task, useAppState } from '@/contexts/AppStateContext';
import { cn } from '@/lib/utils';
import { CaseSelector } from '@/components/ui/relationship-selector';
import { ContextBadge } from '@/components/ui/context-badge';
import { useRelationships } from '@/hooks/useRelationships';
import { useContextualForms } from '@/hooks/useContextualForms';
import { EmployeeSelector } from '@/components/ui/employee-selector';

interface TaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  task?: Task | null;
  mode: 'create' | 'edit' | 'view';
}

export const TaskModal: React.FC<TaskModalProps> = ({ 
  isOpen, 
  onClose, 
  task: taskData, 
  mode,
  contextCaseId, 
  contextClientId 
}: TaskModalProps & { contextCaseId?: string; contextClientId?: string }) => {
  const { state, dispatch } = useAppState();
  const { validateTaskCase, getCaseWithClient } = useRelationships();
  const { context, updateContext, getAvailableCases, getContextDetails } = useContextualForms({
    caseId: contextCaseId,
    clientId: contextClientId
  });
  
  const [formData, setFormData] = useState<{
    title: string;
    description: string;
    caseId: string;
    stage: string;
    priority: 'Critical' | 'High' | 'Medium' | 'Low';
    status: 'Not Started' | 'In Progress' | 'Review' | 'Completed' | 'Overdue';
    assignedToId: string;
    assignedToName: string;
    estimatedHours: number;
    dueDate: Date;
  }>({
    title: '',
    description: '',
    caseId: contextCaseId || '',
    stage: '',
    priority: 'Medium',
    status: 'Not Started',
    assignedToId: '',
    assignedToName: '',
    estimatedHours: 8,
    dueDate: new Date()
  });

  useEffect(() => {
    if (taskData && (mode === 'edit' || mode === 'view')) {
      setFormData({
        title: taskData.title,
        description: taskData.description,
        caseId: taskData.caseId,
        stage: taskData.stage,
        priority: taskData.priority,
        status: taskData.status,
        assignedToId: taskData.assignedToId,
        assignedToName: taskData.assignedToName,
        estimatedHours: taskData.estimatedHours,
        dueDate: new Date(taskData.dueDate)
      });
      updateContext({ caseId: taskData.caseId, clientId: taskData.clientId });
    } else if (mode === 'create') {
      setFormData({
        title: '',
        description: '',
        caseId: contextCaseId || '',
        stage: '',
        priority: 'Medium',
        status: 'Not Started',
        assignedToId: '',
        assignedToName: '',
        estimatedHours: 8,
        dueDate: new Date()
      });
    }
  }, [taskData, mode, contextCaseId, updateContext]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Validate case relationship
    const caseValidation = validateTaskCase(formData.caseId);
    if (!caseValidation.isValid) {
      toast({
        title: "Validation Error",
        description: caseValidation.errors.join(', '),
        variant: "destructive"
      });
      return;
    }

    // Get case and client info for auto-derivation
    const caseWithClient = getCaseWithClient(formData.caseId);
    if (!caseWithClient?.case || !caseWithClient?.client) {
      toast({
        title: "Error",
        description: "Could not find case or client information.",
        variant: "destructive"
      });
      return;
    }
    
    if (mode === 'create') {
      const newTask: Task = {
        id: Date.now().toString(),
        title: formData.title,
        description: formData.description,
        caseId: formData.caseId,
        clientId: caseWithClient.client.id, // Auto-derived from case
        caseNumber: caseWithClient.case.caseNumber, // Auto-derived from case
        stage: formData.stage,
        priority: formData.priority,
        status: formData.status,
        assignedToId: formData.assignedToId,
        assignedToName: formData.assignedToName,
        assignedById: '3', // Current User ID - in real app, get from auth context
        assignedByName: 'Mike Wilson', // Current User Name - in real app, get from auth context
        createdDate: new Date().toISOString().split('T')[0],
        dueDate: formData.dueDate.toISOString().split('T')[0],
        estimatedHours: formData.estimatedHours,
        isAutoGenerated: false,
        escalationLevel: 0
      };

      dispatch({ type: 'ADD_TASK', payload: newTask });
      toast({
        title: "Task Created",
        description: `Task "${formData.title}" has been created successfully.`,
      });
    } else if (mode === 'edit' && taskData) {
      const updatedTask: Task = {
        ...taskData,
        title: formData.title,
        description: formData.description,
        priority: formData.priority,
        status: formData.status,
        assignedToId: formData.assignedToId,
        assignedToName: formData.assignedToName,
        estimatedHours: formData.estimatedHours,
        dueDate: formData.dueDate.toISOString().split('T')[0]
        // Note: caseId, clientId, caseNumber are not updatable in edit mode
      };

      dispatch({ type: 'UPDATE_TASK', payload: updatedTask });
      toast({
        title: "Task Updated",
        description: `Task "${formData.title}" has been updated successfully.`,
      });
    }

    onClose();
  };

  const handleDelete = () => {
    if (taskData) {
      dispatch({ type: 'DELETE_TASK', payload: taskData.id });
      toast({
        title: "Task Deleted",
        description: `Task "${taskData.title}" has been deleted.`,
      });
      onClose();
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>
            {mode === 'create' && 'Create New Task'}
            {mode === 'edit' && 'Edit Task'}
            {mode === 'view' && 'Task Details'}
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <Label htmlFor="title">Task Title</Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
              disabled={mode === 'view'}
              required
            />
          </div>

          <div>
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              disabled={mode === 'view'}
              rows={3}
            />
          </div>

          {/* Context Information */}
          {context.clientId && (
            <div className="space-y-2">
              <ContextBadge
                label="Client"
                value={getContextDetails().client?.name || 'Unknown Client'}
                variant="outline"
              />
            </div>
          )}

          <div className="grid grid-cols-2 gap-4">
            <div>
              {contextCaseId ? (
                <div className="space-y-2">
                  <ContextBadge
                    label="Case"
                    value={getContextDetails().case?.caseNumber || 'Unknown Case'}
                    variant="outline"
                  />
                </div>
              ) : (
                <CaseSelector
                  cases={getAvailableCases()}
                  value={formData.caseId}
                  onValueChange={(value) => {
                    const selectedCase = state.cases.find(c => c.id === value);
                    if (selectedCase) {
                      setFormData(prev => ({ 
                        ...prev, 
                        caseId: value,
                        stage: selectedCase.currentStage
                      }));
                      updateContext({ caseId: value });
                    }
                  }}
                  disabled={mode === 'view'}
                />
              )}
            </div>
            <div>
              <Label htmlFor="stage">Stage</Label>
              <Input
                id="stage"
                value={formData.stage}
                onChange={(e) => setFormData(prev => ({ ...prev, stage: e.target.value }))}
                disabled={mode === 'view'}
                required
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="priority">Priority</Label>
              <Select 
                value={formData.priority} 
                onValueChange={(value) => setFormData(prev => ({ ...prev, priority: value as any }))}
                disabled={mode === 'view'}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Critical">Critical</SelectItem>
                  <SelectItem value="High">High</SelectItem>
                  <SelectItem value="Medium">Medium</SelectItem>
                  <SelectItem value="Low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label htmlFor="status">Status</Label>
              <Select 
                value={formData.status} 
                onValueChange={(value) => setFormData(prev => ({ ...prev, status: value as any }))}
                disabled={mode === 'view'}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Not Started">Not Started</SelectItem>
                  <SelectItem value="In Progress">In Progress</SelectItem>
                  <SelectItem value="Review">Review</SelectItem>
                  <SelectItem value="Completed">Completed</SelectItem>
                  <SelectItem value="Overdue">Overdue</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <EmployeeSelector
                value={formData.assignedToId}
                onValueChange={(value) => {
                  const employee = state.employees.find(e => e.id === value);
                  setFormData(prev => ({ 
                    ...prev, 
                    assignedToId: value,
                    assignedToName: employee?.full_name || ''
                  }));
                }}
                disabled={mode === 'view'}
                required
                showWorkload
              />
            </div>
            <div>
              <Label htmlFor="estimatedHours">Estimated Hours</Label>
              <Input
                id="estimatedHours"
                type="number"
                value={formData.estimatedHours}
                onChange={(e) => setFormData(prev => ({ ...prev, estimatedHours: parseInt(e.target.value) || 0 }))}
                disabled={mode === 'view'}
                min="1"
                required
              />
            </div>
          </div>

          <div>
            <Label>Due Date</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    "w-full justify-start text-left font-normal",
                    !formData.dueDate && "text-muted-foreground"
                  )}
                  disabled={mode === 'view'}
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {formData.dueDate ? format(formData.dueDate, "PPP") : <span>Pick a date</span>}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  mode="single"
                  selected={formData.dueDate}
                  onSelect={(date) => date && setFormData(prev => ({ ...prev, dueDate: date }))}
                  initialFocus
                  className="pointer-events-auto"
                />
              </PopoverContent>
            </Popover>
          </div>

          <div className="flex justify-end space-x-2 pt-4">
            <Button type="button" variant="outline" onClick={onClose}>
              {mode === 'view' ? 'Close' : 'Cancel'}
            </Button>
            {mode === 'edit' && (
              <Button type="button" variant="destructive" onClick={handleDelete}>
                Delete Task
              </Button>
            )}
            {mode !== 'view' && (
              <Button type="submit">
                {mode === 'create' ? 'Create Task' : 'Update Task'}
              </Button>
            )}
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};