import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { CalendarIcon } from 'lucide-react';
import { format } from 'date-fns';
import { toast } from '@/hooks/use-toast';
import { Task, useAppState } from '@/contexts/AppStateContext';
import { cn } from '@/lib/utils';

interface TaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  task?: Task | null;
  mode: 'create' | 'edit' | 'view';
}

export const TaskModal: React.FC<TaskModalProps> = ({ isOpen, onClose, task: taskData, mode }) => {
  const { state, dispatch } = useAppState();
  const [formData, setFormData] = useState<{
    title: string;
    description: string;
    caseId: string;
    caseNumber: string;
    stage: string;
    priority: 'Critical' | 'High' | 'Medium' | 'Low';
    status: 'Not Started' | 'In Progress' | 'Review' | 'Completed' | 'Overdue';
    assignedTo: string;
    estimatedHours: number;
    dueDate: Date;
  }>({
    title: '',
    description: '',
    caseId: '',
    caseNumber: '',
    stage: '',
    priority: 'Medium',
    status: 'Not Started',
    assignedTo: '',
    estimatedHours: 8,
    dueDate: new Date()
  });

  useEffect(() => {
    if (taskData && (mode === 'edit' || mode === 'view')) {
      setFormData({
        title: taskData.title,
        description: taskData.description,
        caseId: taskData.caseId,
        caseNumber: taskData.caseNumber,
        stage: taskData.stage,
        priority: taskData.priority,
        status: taskData.status,
        assignedTo: taskData.assignedTo,
        estimatedHours: taskData.estimatedHours,
        dueDate: new Date(taskData.dueDate)
      });
    } else if (mode === 'create') {
      setFormData({
        title: '',
        description: '',
        caseId: '',
        caseNumber: '',
        stage: '',
        priority: 'Medium',
        status: 'Not Started',
        assignedTo: '',
        estimatedHours: 8,
        dueDate: new Date()
      });
    }
  }, [taskData, mode]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (mode === 'create') {
      const newTask: Task = {
        id: Date.now().toString(),
        title: formData.title,
        description: formData.description,
        caseId: formData.caseId,
        caseNumber: formData.caseNumber,
        stage: formData.stage,
        priority: formData.priority,
        status: formData.status,
        assignedTo: formData.assignedTo,
        assignedBy: 'Current User', // In real app, get from auth context
        createdDate: new Date().toISOString().split('T')[0],
        dueDate: formData.dueDate.toISOString().split('T')[0],
        estimatedHours: formData.estimatedHours,
        isAutoGenerated: false,
        escalationLevel: 0
      };

      dispatch({ type: 'ADD_TASK', payload: newTask });
      toast({
        title: "Task Created",
        description: `Task "${formData.title}" has been created successfully.`,
      });
    } else if (mode === 'edit' && taskData) {
      const updatedTask: Task = {
        ...taskData,
        title: formData.title,
        description: formData.description,
        priority: formData.priority,
        status: formData.status,
        assignedTo: formData.assignedTo,
        estimatedHours: formData.estimatedHours,
        dueDate: formData.dueDate.toISOString().split('T')[0]
      };

      dispatch({ type: 'UPDATE_TASK', payload: updatedTask });
      toast({
        title: "Task Updated",
        description: `Task "${formData.title}" has been updated successfully.`,
      });
    }

    onClose();
  };

  const handleDelete = () => {
    if (taskData) {
      dispatch({ type: 'DELETE_TASK', payload: taskData.id });
      toast({
        title: "Task Deleted",
        description: `Task "${taskData.title}" has been deleted.`,
      });
      onClose();
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>
            {mode === 'create' && 'Create New Task'}
            {mode === 'edit' && 'Edit Task'}
            {mode === 'view' && 'Task Details'}
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <Label htmlFor="title">Task Title</Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
              disabled={mode === 'view'}
              required
            />
          </div>

          <div>
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              disabled={mode === 'view'}
              rows={3}
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="caseNumber">Case Number</Label>
              <Select 
                value={formData.caseNumber} 
                onValueChange={(value) => {
                  const selectedCase = state.cases.find(c => c.caseNumber === value);
                  if (selectedCase) {
                    setFormData(prev => ({ 
                      ...prev, 
                      caseNumber: value,
                      caseId: selectedCase.id,
                      stage: selectedCase.currentStage
                    }));
                  }
                }}
                disabled={mode === 'view'}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select case" />
                </SelectTrigger>
                <SelectContent>
                  {state.cases.map((case_) => (
                    <SelectItem key={case_.id} value={case_.caseNumber}>
                      {case_.caseNumber} - {case_.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label htmlFor="stage">Stage</Label>
              <Input
                id="stage"
                value={formData.stage}
                onChange={(e) => setFormData(prev => ({ ...prev, stage: e.target.value }))}
                disabled={mode === 'view'}
                required
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="priority">Priority</Label>
              <Select 
                value={formData.priority} 
                onValueChange={(value) => setFormData(prev => ({ ...prev, priority: value as any }))}
                disabled={mode === 'view'}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Critical">Critical</SelectItem>
                  <SelectItem value="High">High</SelectItem>
                  <SelectItem value="Medium">Medium</SelectItem>
                  <SelectItem value="Low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label htmlFor="status">Status</Label>
              <Select 
                value={formData.status} 
                onValueChange={(value) => setFormData(prev => ({ ...prev, status: value as any }))}
                disabled={mode === 'view'}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Not Started">Not Started</SelectItem>
                  <SelectItem value="In Progress">In Progress</SelectItem>
                  <SelectItem value="Review">Review</SelectItem>
                  <SelectItem value="Completed">Completed</SelectItem>
                  <SelectItem value="Overdue">Overdue</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="assignedTo">Assigned To</Label>
              <Input
                id="assignedTo"
                value={formData.assignedTo}
                onChange={(e) => setFormData(prev => ({ ...prev, assignedTo: e.target.value }))}
                disabled={mode === 'view'}
                required
              />
            </div>
            <div>
              <Label htmlFor="estimatedHours">Estimated Hours</Label>
              <Input
                id="estimatedHours"
                type="number"
                value={formData.estimatedHours}
                onChange={(e) => setFormData(prev => ({ ...prev, estimatedHours: parseInt(e.target.value) || 0 }))}
                disabled={mode === 'view'}
                min="1"
                required
              />
            </div>
          </div>

          <div>
            <Label>Due Date</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    "w-full justify-start text-left font-normal",
                    !formData.dueDate && "text-muted-foreground"
                  )}
                  disabled={mode === 'view'}
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {formData.dueDate ? format(formData.dueDate, "PPP") : <span>Pick a date</span>}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  mode="single"
                  selected={formData.dueDate}
                  onSelect={(date) => date && setFormData(prev => ({ ...prev, dueDate: date }))}
                  initialFocus
                  className="pointer-events-auto"
                />
              </PopoverContent>
            </Popover>
          </div>

          <div className="flex justify-end space-x-2 pt-4">
            <Button type="button" variant="outline" onClick={onClose}>
              {mode === 'view' ? 'Close' : 'Cancel'}
            </Button>
            {mode === 'edit' && (
              <Button type="button" variant="destructive" onClick={handleDelete}>
                Delete Task
              </Button>
            )}
            {mode !== 'view' && (
              <Button type="submit">
                {mode === 'create' ? 'Create Task' : 'Update Task'}
              </Button>
            )}
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};