import React from 'react';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import {
  ArrowLeft,
  Calendar,
  Clock,
  User,
  Building2,
  Briefcase,
  Zap,
  PencilLine,
  Package,
  AlertTriangle,
  ChevronRight
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { TaskContextData } from '@/types/taskContext';
import { TASK_STATUS_OPTIONS } from '@/types/taskMessages';
import { cn } from '@/lib/utils';

interface TaskStickyContextHeaderProps {
  context: TaskContextData;
  onBack: () => void;
  children?: React.ReactNode;
}

export const TaskStickyContextHeader: React.FC<TaskStickyContextHeaderProps> = ({
  context,
  onBack,
  children
}) => {
  const navigate = useNavigate();
  const { task, client, case: caseData, bundle, isOverdue, daysOverdue, originLabel } = context;

  const getPriorityConfig = (priority: string) => {
    switch (priority?.toLowerCase()) {
      case 'critical':
        return { color: 'bg-destructive/10 text-destructive border-destructive/20', icon: '🔴' };
      case 'high':
        return { color: 'bg-warning/10 text-warning border-warning/20', icon: '🟠' };
      case 'medium':
        return { color: 'bg-primary/10 text-primary border-primary/20', icon: '🟡' };
      case 'low':
        return { color: 'bg-success/10 text-success border-success/20', icon: '🟢' };
      default:
        return { color: 'bg-muted text-muted-foreground', icon: '⚪' };
    }
  };

  const getStatusConfig = (status: string) => {
    const option = TASK_STATUS_OPTIONS.find(
      (opt) => opt.value.toLowerCase() === status?.toLowerCase()
    );
    return {
      color: option?.color || 'bg-muted text-muted-foreground',
      label: option?.label || status || 'Not Started'
    };
  };

  const getOriginIcon = () => {
    if (task.isAutoGenerated) {
      return <Zap className="h-3 w-3" />;
    }
    return <PencilLine className="h-3 w-3" />;
  };

  const getOriginColor = () => {
    return task.isAutoGenerated 
      ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400'
      : 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400';
  };

  const getInitials = (name: string) => {
    return name
      .split(' ')
      .map((n) => n[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
  };

  const priorityConfig = getPriorityConfig(task.priority);
  const statusConfig = getStatusConfig(task.status);

  return (
    <div className="sticky top-0 z-20 border-b bg-gradient-to-r from-card via-card to-muted/50 shadow-sm">
      {/* Primary Header Row */}
      <div className="px-4 py-3 flex items-center gap-3">
        <Button
          variant="ghost"
          size="icon"
          onClick={onBack}
          className="shrink-0"
        >
          <ArrowLeft className="h-4 w-4" />
        </Button>

        {/* Priority Badge */}
        <Badge variant="outline" className={cn('shrink-0', priorityConfig.color)}>
          {task.priority}
        </Badge>

        {/* Task Title */}
        <h1 className="flex-1 text-lg font-semibold truncate">{task.title}</h1>

        {/* Status Badge */}
        <Badge variant="secondary" className={cn('shrink-0', statusConfig.color)}>
          {statusConfig.label}
        </Badge>

        {/* Action Buttons (passed from parent) */}
        {children}
      </div>

      {/* Context Info Row */}
      <div className="px-4 pb-3 pt-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 text-sm">
        {/* Client */}
        <div className="flex items-center gap-2">
          <Building2 className="h-4 w-4 text-muted-foreground shrink-0" />
          <span className="text-muted-foreground shrink-0">Client:</span>
          {client ? (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="link"
                    className="h-auto p-0 text-sm font-medium text-foreground hover:text-primary truncate"
                    onClick={() => navigate(`/clients/${client.id}`)}
                  >
                    {client.displayName}
                    <ChevronRight className="h-3 w-3 ml-1" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <div className="space-y-1">
                    <p className="font-medium">{client.displayName}</p>
                    {client.pan && <p className="text-xs">PAN: {client.pan}</p>}
                    {client.gstin && <p className="text-xs">GSTIN: {client.gstin}</p>}
                  </div>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ) : (
            <span className="text-muted-foreground italic">Not linked</span>
          )}
        </div>

        {/* Case */}
        <div className="flex items-center gap-2">
          <Briefcase className="h-4 w-4 text-muted-foreground shrink-0" />
          <span className="text-muted-foreground shrink-0">Case:</span>
          {caseData ? (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="link"
                    className="h-auto p-0 text-sm font-medium text-foreground hover:text-primary truncate"
                    onClick={() => navigate(`/cases/${caseData.id}`)}
                  >
                    {caseData.caseNumber}
                    <ChevronRight className="h-3 w-3 ml-1" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <div className="space-y-1">
                    <p className="font-medium">{caseData.caseNumber}</p>
                    <p className="text-xs">{caseData.title}</p>
                    <p className="text-xs">Stage: {caseData.currentStage || 'N/A'}</p>
                    {caseData.caseType && <p className="text-xs">Type: {caseData.caseType}</p>}
                  </div>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ) : (
            <span className="text-muted-foreground italic">Not linked</span>
          )}
          {caseData?.stageAtTaskCreation && (
            <Badge variant="outline" className="text-xs ml-1">
              @ {caseData.stageAtTaskCreation}
            </Badge>
          )}
        </div>

        {/* Due Date */}
        <div className="flex items-center gap-2">
          <Calendar className="h-4 w-4 text-muted-foreground shrink-0" />
          <span className="text-muted-foreground shrink-0">Due:</span>
          {task.dueDate ? (
            <div className={cn(
              'flex items-center gap-1.5',
              isOverdue && 'text-destructive font-medium'
            )}>
              <span>{format(new Date(task.dueDate), 'MMM d, yyyy')}</span>
              {isOverdue && (
                <Badge variant="destructive" className="text-xs flex items-center gap-1">
                  <AlertTriangle className="h-3 w-3" />
                  {daysOverdue}d overdue
                </Badge>
              )}
            </div>
          ) : (
            <span className="text-muted-foreground italic">No due date</span>
          )}
        </div>

        {/* Assignee */}
        <div className="flex items-center gap-2">
          <User className="h-4 w-4 text-muted-foreground shrink-0" />
          <span className="text-muted-foreground shrink-0">Assignee:</span>
          {task.assignedToName ? (
            <div className="flex items-center gap-1.5">
              <Avatar className="h-5 w-5">
                <AvatarFallback className="text-[10px] bg-primary/10 text-primary">
                  {getInitials(task.assignedToName)}
                </AvatarFallback>
              </Avatar>
              <span className="truncate">{task.assignedToName}</span>
            </div>
          ) : (
            <span className="text-muted-foreground italic">Unassigned</span>
          )}
        </div>
      </div>

      {/* Tertiary Row - Origin & Bundle */}
      <div className="px-4 pb-3 flex items-center gap-3 flex-wrap text-sm border-t border-border/50 pt-2 bg-muted/20">
        {/* Origin Badge */}
        <div className="flex items-center gap-2">
          <span className="text-muted-foreground">Origin:</span>
          <Badge variant="secondary" className={cn('flex items-center gap-1', getOriginColor())}>
            {getOriginIcon()}
            {originLabel}
          </Badge>
        </div>

        {/* Bundle Reference */}
        {bundle && (
          <div className="flex items-center gap-2">
            <Package className="h-4 w-4 text-muted-foreground" />
            <span className="text-muted-foreground">Bundle:</span>
            <Badge variant="outline" className="flex items-center gap-1">
              {bundle.name}
              <span className="text-xs text-muted-foreground">
                ({bundle.completedTasks}/{bundle.totalTasks})
              </span>
            </Badge>
          </div>
        )}

        {/* Created Date */}
        {task.createdDate && (
          <div className="flex items-center gap-2 ml-auto text-muted-foreground">
            <Clock className="h-3.5 w-3.5" />
            <span>Created: {format(new Date(task.createdDate), 'MMM d, yyyy')}</span>
          </div>
        )}
      </div>
    </div>
  );
};
