import React from 'react';
import { format } from 'date-fns';
import { 
  Calendar, 
  User, 
  Flag, 
  Clock,
  Briefcase,
  ChevronRight
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Task } from '@/contexts/AppStateContext';
import { TASK_STATUS_OPTIONS } from '@/types/taskMessages';
import { cn } from '@/lib/utils';

interface TaskHeaderProps {
  task: Task;
  compact?: boolean;
}

export const TaskHeader: React.FC<TaskHeaderProps> = ({ task, compact = false }) => {
  const getPriorityConfig = (priority: string) => {
    switch (priority?.toLowerCase()) {
      case 'critical':
        return { color: 'bg-destructive/10 text-destructive border-destructive/20', icon: '🔴' };
      case 'high':
        return { color: 'bg-warning/10 text-warning border-warning/20', icon: '🟠' };
      case 'medium':
        return { color: 'bg-primary/10 text-primary border-primary/20', icon: '🟡' };
      case 'low':
        return { color: 'bg-success/10 text-success border-success/20', icon: '🟢' };
      default:
        return { color: 'bg-muted text-muted-foreground', icon: '⚪' };
    }
  };

  const getStatusConfig = (status: string) => {
    const option = TASK_STATUS_OPTIONS.find(
      (opt) => opt.value.toLowerCase() === status?.toLowerCase()
    );
    return {
      color: option?.color || 'bg-muted text-muted-foreground',
      label: option?.label || status || 'Not Started'
    };
  };

  const getDueStatus = () => {
    if (!task.dueDate) return null;
    const due = new Date(task.dueDate);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    due.setHours(0, 0, 0, 0);
    
    const diffDays = Math.ceil((due.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
    
    if (diffDays < 0) return { text: `${Math.abs(diffDays)}d overdue`, urgent: true };
    if (diffDays === 0) return { text: 'Due today', urgent: true };
    if (diffDays === 1) return { text: 'Due tomorrow', urgent: false };
    return { text: `${diffDays}d left`, urgent: false };
  };

  const priorityConfig = getPriorityConfig(task.priority);
  const statusConfig = getStatusConfig(task.status || '');
  const dueStatus = getDueStatus();

  const getInitials = (name: string) => {
    return name
      .split(' ')
      .map((n) => n[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
  };

  if (compact) {
    return (
      <div className="flex items-center gap-3 py-2">
        <Badge variant="secondary" className={cn('text-xs font-medium', statusConfig.color)}>
          {statusConfig.label}
        </Badge>
        {task.assignedToName && (
          <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
            <Avatar className="h-5 w-5">
              <AvatarFallback className="text-[10px] bg-muted">
                {getInitials(task.assignedToName)}
              </AvatarFallback>
            </Avatar>
            <span className="hidden sm:inline">{task.assignedToName}</span>
          </div>
        )}
        {task.dueDate && (
          <div className={cn(
            'flex items-center gap-1 text-sm',
            dueStatus?.urgent ? 'text-destructive' : 'text-muted-foreground'
          )}>
            <Calendar className="h-3.5 w-3.5" />
            <span>{format(new Date(task.dueDate), 'MMM d')}</span>
            {dueStatus && (
              <span className="text-xs">({dueStatus.text})</span>
            )}
          </div>
        )}
        {task.priority && (
          <Badge variant="outline" className={cn('text-xs', priorityConfig.color)}>
            {task.priority}
          </Badge>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {/* Status & Priority Row */}
      <div className="flex items-center gap-2 flex-wrap">
        <Badge variant="secondary" className={cn('font-medium', statusConfig.color)}>
          {statusConfig.label}
        </Badge>
        {task.priority && (
          <Badge variant="outline" className={cn('font-medium', priorityConfig.color)}>
            <Flag className="h-3 w-3 mr-1" />
            {task.priority}
          </Badge>
        )}
        {task.isAutoGenerated && (
          <Badge variant="secondary" className="bg-accent/10 text-accent-foreground text-xs">
            Auto-generated
          </Badge>
        )}
      </div>

      {/* Meta Info Row */}
      <div className="flex items-center gap-4 text-sm text-muted-foreground flex-wrap">
        {task.assignedToName && (
          <div className="flex items-center gap-1.5">
            <Avatar className="h-5 w-5">
              <AvatarFallback className="text-[10px] bg-muted">
                {getInitials(task.assignedToName)}
              </AvatarFallback>
            </Avatar>
            <span>{task.assignedToName}</span>
          </div>
        )}
        
        {task.dueDate && (
          <div className={cn(
            'flex items-center gap-1',
            dueStatus?.urgent ? 'text-destructive font-medium' : ''
          )}>
            <Calendar className="h-3.5 w-3.5" />
            <span>{format(new Date(task.dueDate), 'MMM d, yyyy')}</span>
            {dueStatus && (
              <span className={cn(
                'text-xs px-1.5 py-0.5 rounded-full',
                dueStatus.urgent ? 'bg-destructive/10' : 'bg-muted'
              )}>
                {dueStatus.text}
              </span>
            )}
          </div>
        )}

        {task.estimatedHours && task.estimatedHours > 0 && (
          <div className="flex items-center gap-1">
            <Clock className="h-3.5 w-3.5" />
            <span>{task.estimatedHours}h est.</span>
          </div>
        )}

        {task.caseNumber && (
          <div className="flex items-center gap-1">
            <Briefcase className="h-3.5 w-3.5" />
            <span>{task.caseNumber}</span>
          </div>
        )}
      </div>
    </div>
  );
};
