import React, { useState } from 'react';
import { toast } from '@/hooks/use-toast';
import { motion } from 'framer-motion';
import { 
  CheckSquare, 
  Clock, 
  AlertTriangle, 
  User,
  Plus,
  Filter,
  Search,
  Calendar,
  Bell,
  ArrowUp,
  FileText,
  Users,
  Target,
  TrendingUp
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { TaskBoard } from './TaskBoard';
import { TaskAutomation } from './TaskAutomation';
import { EscalationMatrix } from './EscalationMatrix';
import { TaskTemplates } from './TaskTemplates';

interface Task {
  id: string;
  title: string;
  description: string;
  caseId: string;
  caseNumber: string;
  stage: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  status: 'Not Started' | 'In Progress' | 'Review' | 'Completed' | 'Overdue';
  assignedTo: string;
  assignedBy: string;
  createdDate: string;
  dueDate: string;
  completedDate?: string;
  estimatedHours: number;
  actualHours?: number;
  isAutoGenerated: boolean;
  bundleId?: string;
  dependencies?: string[];
  attachments?: string[];
  escalationLevel: 0 | 1 | 2 | 3; // 0: Normal, 1: Manager, 2: Partner, 3: Senior Partner
}

interface TaskBundle {
  id: string;
  name: string;
  stage: string;
  tasks: string[];
  autoTrigger: boolean;
  sequenceRequired: boolean;
}

const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Draft Response to DRC-01 Notice',
    description: 'Prepare comprehensive response addressing all points raised in the demand notice',
    caseId: '1',
    caseNumber: 'CASE-2024-001',
    stage: 'Demand',
    priority: 'Critical',
    status: 'Overdue',
    assignedTo: 'John Smith',
    assignedBy: 'Mike Wilson',
    createdDate: '2024-01-15',
    dueDate: '2024-01-20',
    estimatedHours: 16,
    actualHours: 20,
    isAutoGenerated: true,
    bundleId: 'demand-response-bundle',
    escalationLevel: 2
  },
  {
    id: '2',
    title: 'Prepare Supporting Annexures',
    description: 'Compile all required supporting documents and evidence',
    caseId: '1',
    caseNumber: 'CASE-2024-001',
    stage: 'Demand',
    priority: 'High',
    status: 'In Progress',
    assignedTo: 'Sarah Johnson',
    assignedBy: 'John Smith',
    createdDate: '2024-01-16',
    dueDate: '2024-01-22',
    estimatedHours: 8,
    actualHours: 6,
    isAutoGenerated: true,
    bundleId: 'demand-response-bundle',
    dependencies: ['1'],
    escalationLevel: 1
  },
  {
    id: '3',
    title: 'Legal Review - Constitutional Arguments',
    description: 'Review constitutional aspects for Supreme Court matter',
    caseId: '3',
    caseNumber: 'CASE-2024-003',
    stage: 'SC',
    priority: 'Critical',
    status: 'Review',
    assignedTo: 'Mike Wilson',
    assignedBy: 'Senior Partner',
    createdDate: '2024-01-18',
    dueDate: '2024-02-10',
    estimatedHours: 24,
    actualHours: 18,
    isAutoGenerated: false,
    escalationLevel: 0
  },
  {
    id: '4',
    title: 'File Appeal with GSTAT',
    description: 'Prepare and file appeal with GST Appellate Tribunal',
    caseId: '2',
    caseNumber: 'CASE-2024-002',
    stage: 'GSTAT',
    priority: 'Medium',
    status: 'Not Started',
    assignedTo: 'Sarah Johnson',
    assignedBy: 'John Smith',
    createdDate: '2024-01-20',
    dueDate: '2024-02-05',
    estimatedHours: 12,
    isAutoGenerated: true,
    bundleId: 'gstat-appeal-bundle',
    escalationLevel: 0
  }
];

const taskBundles: TaskBundle[] = [
  {
    id: 'demand-response-bundle',
    name: 'Demand Notice Response',
    stage: 'Demand',
    tasks: ['draft-response', 'prepare-annexures', 'legal-review', 'client-approval'],
    autoTrigger: true,
    sequenceRequired: true
  },
  {
    id: 'adjudication-bundle',
    name: 'Adjudication Preparation',
    stage: 'Adjudication',
    tasks: ['file-response', 'evidence-compilation', 'hearing-prep'],
    autoTrigger: true,
    sequenceRequired: false
  },
  {
    id: 'appeal-bundle',
    name: 'Appeal Process',
    stage: 'Appeals',
    tasks: ['draft-appeal', 'grounds-preparation', 'precedent-research'],
    autoTrigger: true,
    sequenceRequired: true
  }
];

export const TaskManagement: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState<'all' | Task['status']>('all');
  const [filterPriority, setFilterPriority] = useState<'all' | Task['priority']>('all');

  const filteredTasks = mockTasks.filter(task => {
    const matchesSearch = task.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         task.caseNumber.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = filterStatus === 'all' || task.status === filterStatus;
    const matchesPriority = filterPriority === 'all' || task.priority === filterPriority;
    return matchesSearch && matchesStatus && matchesPriority;
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Completed': return 'bg-success text-success-foreground';
      case 'In Progress': return 'bg-primary text-primary-foreground';
      case 'Review': return 'bg-warning text-warning-foreground';
      case 'Overdue': return 'bg-destructive text-destructive-foreground';
      case 'Not Started': return 'bg-muted text-muted-foreground';
      default: return 'bg-muted text-muted-foreground';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'Critical': return 'bg-destructive text-destructive-foreground';
      case 'High': return 'bg-warning text-warning-foreground';
      case 'Medium': return 'bg-primary text-primary-foreground';
      case 'Low': return 'bg-success text-success-foreground';
      default: return 'bg-muted text-muted-foreground';
    }
  };

  const getTaskStats = () => {
    const total = mockTasks.length;
    const completed = mockTasks.filter(t => t.status === 'Completed').length;
    const overdue = mockTasks.filter(t => t.status === 'Overdue').length;
    const inProgress = mockTasks.filter(t => t.status === 'In Progress').length;
    const autoGenerated = mockTasks.filter(t => t.isAutoGenerated).length;
    
    return { total, completed, overdue, inProgress, autoGenerated };
  };

  const stats = getTaskStats();

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
        className="flex justify-between items-center"
      >
        <div>
          <h1 className="text-3xl font-bold text-foreground">Task Automation & Management</h1>
          <p className="text-muted-foreground mt-2">
            Stage-based auto-task creation with escalation workflows and deadline management
          </p>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline"
            onClick={() => {
              toast({
                title: "Escalations",
                description: "Opening escalation management panel",
              });
            }}
          >
            <Bell className="mr-2 h-4 w-4" />
            Escalations
          </Button>
          <Button 
            className="bg-primary hover:bg-primary-hover"
            onClick={() => {
              toast({
                title: "Create Task",
                description: "Opening task creation form",
              });
            }}
          >
            <Plus className="mr-2 h-4 w-4" />
            Create Task
          </Button>
        </div>
      </motion.div>

      {/* Key Metrics */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.1 }}
        className="grid grid-cols-1 md:grid-cols-5 gap-6"
      >
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Total Tasks</p>
                <p className="text-2xl font-bold text-foreground">{stats.total}</p>
              </div>
              <CheckSquare className="h-8 w-8 text-primary" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Completed</p>
                <p className="text-2xl font-bold text-success">{stats.completed}</p>
                <p className="text-xs text-success mt-1">{Math.round((stats.completed / stats.total) * 100)}% completion</p>
              </div>
              <Target className="h-8 w-8 text-success" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Overdue</p>
                <p className="text-2xl font-bold text-destructive">{stats.overdue}</p>
                <p className="text-xs text-destructive mt-1">Needs escalation</p>
              </div>
              <AlertTriangle className="h-8 w-8 text-destructive" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">In Progress</p>
                <p className="text-2xl font-bold text-primary">{stats.inProgress}</p>
              </div>
              <Clock className="h-8 w-8 text-primary" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Auto-Generated</p>
                <p className="text-2xl font-bold text-secondary">{stats.autoGenerated}</p>
                <p className="text-xs text-secondary mt-1">{Math.round((stats.autoGenerated / stats.total) * 100)}% automated</p>
              </div>
              <TrendingUp className="h-8 w-8 text-secondary" />
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Search and Filters */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.2 }}
        className="flex flex-col sm:flex-row gap-4 items-center justify-between"
      >
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search tasks by title or case number..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10"
          />
        </div>
        
        <div className="flex gap-2">
          <Button 
            variant="outline"
            onClick={() => {
              toast({
                title: "Filter Status",
                description: "Opening status filter options",
              });
            }}
          >
            <Filter className="mr-2 h-4 w-4" />
            Status: {filterStatus}
          </Button>
          <Button 
            variant="outline"
            onClick={() => {
              toast({
                title: "Filter Priority",
                description: "Opening priority filter options",
              });
            }}
          >
            <User className="mr-2 h-4 w-4" />
            Priority: {filterPriority}
          </Button>
          <Button 
            variant="outline"
            onClick={() => {
              toast({
                title: "Due Date Filter",
                description: "Opening date range selector",
              });
            }}
          >
            <Calendar className="mr-2 h-4 w-4" />
            Due Date
          </Button>
        </div>
      </motion.div>

      {/* Main Content */}
      <Tabs defaultValue="board" className="w-full">
        <TabsList className="grid w-full grid-cols-5">
          <TabsTrigger value="board">Task Board</TabsTrigger>
          <TabsTrigger value="automation">Automation</TabsTrigger>
          <TabsTrigger value="escalation">Escalation</TabsTrigger>
          <TabsTrigger value="templates">Templates</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
        </TabsList>

        <TabsContent value="board" className="mt-6">
          <TaskBoard tasks={filteredTasks} />
        </TabsContent>

        <TabsContent value="automation" className="mt-6">
          <TaskAutomation bundles={taskBundles} />
        </TabsContent>

        <TabsContent value="escalation" className="mt-6">
          <EscalationMatrix tasks={mockTasks} />
        </TabsContent>

        <TabsContent value="templates" className="mt-6">
          <TaskTemplates bundles={taskBundles} />
        </TabsContent>

        <TabsContent value="analytics" className="mt-6">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="grid grid-cols-1 lg:grid-cols-2 gap-6"
          >
            <Card>
              <CardHeader>
                <CardTitle>Task Performance Metrics</CardTitle>
                <CardDescription>
                  Overall task completion and efficiency metrics
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="text-sm font-medium">Completion Rate</span>
                      <span className="text-sm text-muted-foreground">{Math.round((stats.completed / stats.total) * 100)}%</span>
                    </div>
                    <Progress value={(stats.completed / stats.total) * 100} />
                  </div>
                  
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="text-sm font-medium">On-Time Delivery</span>
                      <span className="text-sm text-muted-foreground">87%</span>
                    </div>
                    <Progress value={87} />
                  </div>
                  
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="text-sm font-medium">Automation Rate</span>
                      <span className="text-sm text-muted-foreground">{Math.round((stats.autoGenerated / stats.total) * 100)}%</span>
                    </div>
                    <Progress value={(stats.autoGenerated / stats.total) * 100} />
                  </div>
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle>Escalation Trends</CardTitle>
                <CardDescription>
                  Task escalation patterns and resolution times
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="grid grid-cols-3 gap-4 text-center">
                    <div>
                      <p className="text-2xl font-bold text-success">24</p>
                      <p className="text-xs text-muted-foreground">Resolved at Level 1</p>
                    </div>
                    <div>
                      <p className="text-2xl font-bold text-warning">8</p>
                      <p className="text-xs text-muted-foreground">Escalated to Partner</p>
                    </div>
                    <div>
                      <p className="text-2xl font-bold text-destructive">2</p>
                      <p className="text-xs text-muted-foreground">Senior Partner Level</p>
                    </div>
                  </div>
                  
                  <div className="pt-4">
                    <p className="text-sm font-medium mb-2">Average Resolution Time</p>
                    <p className="text-lg font-bold text-primary">2.4 hours</p>
                    <p className="text-xs text-success">15% faster than last month</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </TabsContent>
      </Tabs>
    </div>
  );
};