import React, { useState } from 'react';
import { toast } from '@/hooks/use-toast';
import { motion } from 'framer-motion';
import { 
  CheckSquare, 
  Clock, 
  AlertTriangle, 
  User,
  Plus,
  Filter,
  Search,
  Calendar,
  Bell,
  ArrowUp,
  FileText,
  Users,
  Target,
  TrendingUp
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { TaskBoard } from './TaskBoard';
import { TaskAutomation } from './TaskAutomation';
import { EscalationMatrix } from './EscalationMatrix';
import { TaskTemplates } from './TaskTemplates';
import { TaskModal } from '@/components/modals/TaskModal';
import { Task, useAppState } from '@/contexts/AppStateContext';

interface TaskBundle {
  id: string;
  name: string;
  stage: string;
  tasks: string[];
  autoTrigger: boolean;
  sequenceRequired: boolean;
}


const taskBundles: TaskBundle[] = [
  {
    id: 'demand-response-bundle',
    name: 'Demand Notice Response',
    stage: 'Demand',
    tasks: ['draft-response', 'prepare-annexures', 'legal-review', 'client-approval'],
    autoTrigger: true,
    sequenceRequired: true
  },
  {
    id: 'adjudication-bundle',
    name: 'Adjudication Preparation',
    stage: 'Adjudication',
    tasks: ['file-response', 'evidence-compilation', 'hearing-prep'],
    autoTrigger: true,
    sequenceRequired: false
  },
  {
    id: 'appeal-bundle',
    name: 'Appeal Process',
    stage: 'Appeals',
    tasks: ['draft-appeal', 'grounds-preparation', 'precedent-research'],
    autoTrigger: true,
    sequenceRequired: true
  }
];

export const TaskManagement: React.FC = () => {
  const { state } = useAppState();
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState<'all' | Task['status']>('all');
  const [filterPriority, setFilterPriority] = useState<'all' | Task['priority']>('all');
  const [taskModal, setTaskModal] = useState<{ isOpen: boolean; mode: 'create' | 'edit' | 'view'; task?: Task | null }>({
    isOpen: false,
    mode: 'create',
    task: null
  });

  const filteredTasks = state.tasks.filter(task => {
    const matchesSearch = task.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         task.caseNumber.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = filterStatus === 'all' || task.status === filterStatus;
    const matchesPriority = filterPriority === 'all' || task.priority === filterPriority;
    return matchesSearch && matchesStatus && matchesPriority;
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Completed': return 'bg-success text-success-foreground';
      case 'In Progress': return 'bg-primary text-primary-foreground';
      case 'Review': return 'bg-warning text-warning-foreground';
      case 'Overdue': return 'bg-destructive text-destructive-foreground';
      case 'Not Started': return 'bg-muted text-muted-foreground';
      default: return 'bg-muted text-muted-foreground';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'Critical': return 'bg-destructive text-destructive-foreground';
      case 'High': return 'bg-warning text-warning-foreground';
      case 'Medium': return 'bg-primary text-primary-foreground';
      case 'Low': return 'bg-success text-success-foreground';
      default: return 'bg-muted text-muted-foreground';
    }
  };

  const getTaskStats = () => {
    const total = state.tasks.length;
    const completed = state.tasks.filter(t => t.status === 'Completed').length;
    const overdue = state.tasks.filter(t => t.status === 'Overdue').length;
    const inProgress = state.tasks.filter(t => t.status === 'In Progress').length;
    const autoGenerated = state.tasks.filter(t => t.isAutoGenerated).length;
    
    return { total, completed, overdue, inProgress, autoGenerated };
  };

  const stats = getTaskStats();

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
        className="flex justify-between items-center"
      >
        <div>
          <h1 className="text-3xl font-bold text-foreground">Task Automation & Management</h1>
          <p className="text-muted-foreground mt-2">
            Stage-based auto-task creation with escalation workflows and deadline management
          </p>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline"
            onClick={() => {
              toast({
                title: "Escalations",
                description: "Opening escalation management panel",
              });
            }}
          >
            <Bell className="mr-2 h-4 w-4" />
            Escalations
          </Button>
          <Button 
            className="bg-primary hover:bg-primary-hover"
            onClick={() => setTaskModal({ isOpen: true, mode: 'create', task: null })}
          >
            <Plus className="mr-2 h-4 w-4" />
            Create Task
          </Button>
        </div>
      </motion.div>

      {/* Key Metrics */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.1 }}
        className="grid grid-cols-1 md:grid-cols-5 gap-6"
      >
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Total Tasks</p>
                <p className="text-2xl font-bold text-foreground">{stats.total}</p>
              </div>
              <CheckSquare className="h-8 w-8 text-primary" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Completed</p>
                <p className="text-2xl font-bold text-success">{stats.completed}</p>
                <p className="text-xs text-success mt-1">{Math.round((stats.completed / stats.total) * 100)}% completion</p>
              </div>
              <Target className="h-8 w-8 text-success" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Overdue</p>
                <p className="text-2xl font-bold text-destructive">{stats.overdue}</p>
                <p className="text-xs text-destructive mt-1">Needs escalation</p>
              </div>
              <AlertTriangle className="h-8 w-8 text-destructive" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">In Progress</p>
                <p className="text-2xl font-bold text-primary">{stats.inProgress}</p>
              </div>
              <Clock className="h-8 w-8 text-primary" />
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Auto-Generated</p>
                <p className="text-2xl font-bold text-secondary">{stats.autoGenerated}</p>
                <p className="text-xs text-secondary mt-1">{Math.round((stats.autoGenerated / stats.total) * 100)}% automated</p>
              </div>
              <TrendingUp className="h-8 w-8 text-secondary" />
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Search and Filters */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.2 }}
        className="flex flex-col sm:flex-row gap-4 items-center justify-between"
      >
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search tasks by title or case number..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10"
          />
        </div>
        
        <div className="flex gap-2">
          <Button 
            variant="outline"
            onClick={() => {
              toast({
                title: "Filter Status",
                description: "Opening status filter options",
              });
            }}
          >
            <Filter className="mr-2 h-4 w-4" />
            Status: {filterStatus}
          </Button>
          <Button 
            variant="outline"
            onClick={() => {
              toast({
                title: "Filter Priority",
                description: "Opening priority filter options",
              });
            }}
          >
            <User className="mr-2 h-4 w-4" />
            Priority: {filterPriority}
          </Button>
          <Button 
            variant="outline"
            onClick={() => {
              toast({
                title: "Due Date Filter",
                description: "Opening date range selector",
              });
            }}
          >
            <Calendar className="mr-2 h-4 w-4" />
            Due Date
          </Button>
        </div>
      </motion.div>

      {/* Main Content */}
      <Tabs defaultValue="board" className="w-full">
        <TabsList className="grid w-full grid-cols-5">
          <TabsTrigger value="board">Task Board</TabsTrigger>
          <TabsTrigger value="automation">Automation</TabsTrigger>
          <TabsTrigger value="escalation">Escalation</TabsTrigger>
          <TabsTrigger value="templates">Templates</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
        </TabsList>

        <TabsContent value="board" className="mt-6">
          <TaskBoard tasks={filteredTasks.map(t => ({ ...t, assignedTo: t.assignedToName }))} />
        </TabsContent>

        <TabsContent value="automation" className="mt-6">
          <TaskAutomation bundles={taskBundles} />
        </TabsContent>

        <TabsContent value="escalation" className="mt-6">
          <EscalationMatrix tasks={state.tasks.map(t => ({ ...t, assignedToName: t.assignedToName }))} />
        </TabsContent>

        <TabsContent value="templates" className="mt-6">
          <TaskTemplates bundles={taskBundles} />
        </TabsContent>

        <TabsContent value="analytics" className="mt-6">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="grid grid-cols-1 lg:grid-cols-2 gap-6"
          >
            <Card>
              <CardHeader>
                <CardTitle>Task Performance Metrics</CardTitle>
                <CardDescription>
                  Overall task completion and efficiency metrics
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="text-sm font-medium">Completion Rate</span>
                      <span className="text-sm text-muted-foreground">{Math.round((stats.completed / stats.total) * 100)}%</span>
                    </div>
                    <Progress value={(stats.completed / stats.total) * 100} />
                  </div>
                  
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="text-sm font-medium">On-Time Delivery</span>
                      <span className="text-sm text-muted-foreground">87%</span>
                    </div>
                    <Progress value={87} />
                  </div>
                  
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="text-sm font-medium">Automation Rate</span>
                      <span className="text-sm text-muted-foreground">{Math.round((stats.autoGenerated / stats.total) * 100)}%</span>
                    </div>
                    <Progress value={(stats.autoGenerated / stats.total) * 100} />
                  </div>
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle>Escalation Trends</CardTitle>
                <CardDescription>
                  Task escalation patterns and resolution times
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="grid grid-cols-3 gap-4 text-center">
                    <div>
                      <p className="text-2xl font-bold text-success">24</p>
                      <p className="text-xs text-muted-foreground">Resolved at Level 1</p>
                    </div>
                    <div>
                      <p className="text-2xl font-bold text-warning">8</p>
                      <p className="text-xs text-muted-foreground">Escalated to Partner</p>
                    </div>
                    <div>
                      <p className="text-2xl font-bold text-destructive">2</p>
                      <p className="text-xs text-muted-foreground">Senior Partner Level</p>
                    </div>
                  </div>
                  
                  <div className="pt-4">
                    <p className="text-sm font-medium mb-2">Average Resolution Time</p>
                    <p className="text-lg font-bold text-primary">2.4 hours</p>
                    <p className="text-xs text-success">15% faster than last month</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </TabsContent>
      </Tabs>

      <TaskModal
        isOpen={taskModal.isOpen}
        onClose={() => setTaskModal({ isOpen: false, mode: 'create', task: null })}
        task={taskModal.task}
        mode={taskModal.mode}
      />
    </div>
  );
};