import React from 'react';
import { Badge } from '@/components/ui/badge';
import { format } from 'date-fns';
import type { IntelligenceData } from '@/services/caseIntelligenceService';

interface Props {
  data: IntelligenceData;
}

const riskColors: Record<string, string> = {
  Low: 'bg-emerald-100 text-emerald-800 border-emerald-300',
  Medium: 'bg-amber-100 text-amber-800 border-amber-300',
  High: 'bg-red-100 text-red-800 border-red-300',
};

export const IntelligenceCover: React.FC<Props> = ({ data }) => {
  const formatCurrency = (n: number) =>
    n >= 10000000 ? `₹${(n / 10000000).toFixed(2)} Cr` :
    n >= 100000 ? `₹${(n / 100000).toFixed(2)} Lakh` :
    `₹${n.toLocaleString('en-IN')}`;

  return (
    <section id="cover" className="print:break-after-page">
      <div className="text-center mb-6">
        <p className="text-xs font-semibold tracking-widest text-destructive uppercase mb-2">
          Confidential — Legal Privilege
        </p>
        <h1 className="text-2xl font-bold text-foreground mb-1">Case Intelligence Report</h1>
        <p className="text-sm text-muted-foreground">{data.case.title}</p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        <InfoCard label="Case Number" value={data.case.caseNumber} />
        <InfoCard label="Client" value={data.case.client} />
        <InfoCard label="Current Stage" value={data.case.currentStage} />
        <div className="bg-muted/50 rounded-lg p-3">
          <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">Risk Level</p>
          <Badge variant="outline" className={riskColors[data.risk.level]}>
            {data.risk.level} ({data.risk.score}/100)
          </Badge>
        </div>
        <InfoCard
          label="Financial Exposure"
          value={data.financial.totalDemand > 0 ? formatCurrency(data.financial.totalDemand) : '—'}
        />
        <InfoCard
          label="Days in Current Stage"
          value={`${data.analytics.daysInCurrentStage} days`}
        />
        <InfoCard
          label="Generated On"
          value={format(new Date(data.generatedAt), 'dd MMM yyyy, HH:mm')}
        />
        <InfoCard label="Generated By" value={data.generatedByName} />
        <InfoCard label="Status" value={data.case.status} />
      </div>
    </section>
  );
};

const InfoCard = ({ label, value }: { label: string; value: string }) => (
  <div className="bg-muted/50 rounded-lg p-3">
    <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">{label}</p>
    <p className="text-sm font-medium text-foreground">{value}</p>
  </div>
);
