// Task Context Types for Enhanced Task Open View

export interface TaskContextData {
  // Core Task Info
  task: {
    id: string;
    title: string;
    description: string;
    status: string;
    priority: string;
    dueDate: string;
    createdDate: string;
    estimatedHours?: number;
    actualHours?: number;
    isAutoGenerated: boolean;
    bundleId?: string;
    assignedToId: string;
    assignedToName: string;
    assignedById?: string;
    assignedByName?: string;
    // New fields
    creationStageCode?: string;
    creationReason?: 'stage_transition' | 'auto_bundle' | 'manual' | 'hearing_scheduled' | 'template' | string;
    taskCategory?: string;
    slaHours?: number;
    createdBy?: string;
    tags?: string[];
  };
  
  // Client Info (required - every task must link to a client)
  client: {
    id: string;
    displayName: string;
    pan?: string;
    gstin?: string;
    email?: string;
    phone?: string;
  } | null;
  
  // Case Info (if task is linked to a case)
  case: {
    id: string;
    caseNumber: string;
    title: string;
    currentStage: string;
    stageAtTaskCreation?: string;
    priority: string;
    status?: string;
    caseType?: string;
    issueType?: string;
    forumName?: string;
    authorityName?: string;
  } | null;
  
  // Bundle Info (if task is part of a bundle)
  bundle: {
    id: string;
    name: string;
    totalTasks: number;
    completedTasks: number;
    siblingTasks: Array<{
      id: string;
      title: string;
      status: string;
      dueDate: string;
    }>;
  } | null;
  
  // Related Items
  linkedDocuments: Array<{
    id: string;
    fileName: string;
    fileType: string;
    fileSize: number;
    category?: string;
    createdAt: string;
  }>;
  
  relatedHearings: Array<{
    id: string;
    hearingDate: string;
    courtName?: string;
    status?: string;
    notes?: string;
  }>;
  
  // Activity Events (for timeline)
  activityEvents: TaskActivityEvent[];
  
  // Computed Properties
  isOverdue: boolean;
  daysOverdue: number;
  originLabel: string;
  slaDeadline?: string;
  slaStatus?: 'on_track' | 'at_risk' | 'breached';
}

export interface TaskActivityEvent {
  id: string;
  type: 'message' | 'status_change' | 'assignment' | 'bundle_creation' | 'stage_trigger' | 'system' | 'client_visible';
  timestamp: string;
  userId: string;
  userName: string;
  content: string;
  metadata?: {
    previousStatus?: string;
    newStatus?: string;
    previousAssignee?: string;
    newAssignee?: string;
    stageName?: string;
    bundleName?: string;
    isClientVisible?: boolean;
    attachments?: Array<{
      id: string;
      name: string;
      url: string;
      type: string;
      size: number;
    }>;
  };
}

export interface ClientVisibilityUpdate {
  messageId: string;
  isClientVisible: boolean;
  approvedAt?: string;
  approvedBy?: string;
}

// Task Creation Context - captures why/how task was created
export interface TaskCreationContext {
  stageCode?: string;
  stageName?: string;
  reason: 'stage_transition' | 'auto_bundle' | 'manual' | 'hearing_scheduled' | 'template';
  bundleId?: string;
  bundleName?: string;
  templateId?: string;
  templateName?: string;
  triggeredBy?: string;
  triggeredAt?: string;
}
