import { Client, Case, Hearing, Task } from '@/contexts/AppStateContext';

interface SampleDataSet {
  client: Omit<Client, 'id'>;
  case: Omit<Case, 'id'>;
  hearing: Omit<Hearing, 'id'>;
  task: Omit<Task, 'id'>;
}

export const generateSampleWorkflow = (): SampleDataSet => {
  const currentDate = new Date();
  const futureDate = (days: number) => {
    const date = new Date(currentDate);
    date.setDate(date.getDate() + days);
    return date.toISOString().split('T')[0];
  };

  return {
    client: {
      name: 'ABC Pvt Ltd',
      type: 'Company',
      companyName: 'ABC Pvt Ltd',
      email: 'info@abc.com',
      phone: '9876543210',
      address: {
        addressLine1: '123 Business Plaza',
        addressLine2: 'Sector 15',
        city: 'Ahmedabad',
        state: 'GJ',
        pincode: '380015',
        country: 'IN'
      },
      panNumber: 'AAAAA0000A',
      gstNumber: '24AAAAA0000A1Z5',
      cin: 'U74999GJ2020PTC123456',
      authorizedSignatory: {
        name: 'Raj Patel',
        designation: 'Managing Director',
        email: 'raj@abc.com',
        phone: '9876543210'
      },
      clientCategory: 'Regular Taxpayer',
      jurisdiction: {
        range: 'Ahmedabad-1',
        division: 'Div-A',
        commissionerate: 'Ahmedabad'
      },
      status: 'Active' as const,
      assignedCAId: '1',
      assignedCAName: 'John Smith',
      defaultAssignedAdvocateId: '2',
      defaultAssignedAdvocateName: 'Sarah Johnson',
      registrationDate: currentDate.toISOString().split('T')[0],
      totalCases: 1,
      activeCases: 1,
      totalInvoiced: 0
    },
    case: {
      caseNumber: `ASMT-${Date.now()}`,
      title: 'ASMT-10 Scrutiny FY23-24',
      clientId: '', // Will be set after client creation
      currentStage: 'Scrutiny',
      priority: 'High',
      slaStatus: 'Amber',
      assignedToId: '1',
      assignedToName: 'John Smith',
      createdDate: currentDate.toISOString().split('T')[0],
      lastUpdated: currentDate.toISOString().split('T')[0],
      documents: 0,
      progress: 25
    },
    hearing: {
      caseId: '', // Will be set after case creation
      clientId: '', // Will be set after client creation
      courtId: '1', // GST Tribunal
      judgeId: '1', // Assuming we have a judge
      date: futureDate(7),
      time: '10:30',
      type: 'Argued',
      status: 'Scheduled',
      agenda: 'Arguments on ASMT-10 scrutiny matter',
      notes: 'Prepare all supporting documents',
      createdDate: currentDate.toISOString().split('T')[0],
      lastUpdated: currentDate.toISOString().split('T')[0]
    },
    task: {
      title: 'Draft Reply to ASMT-10',
      description: 'Prepare comprehensive reply to assessment notice addressing all points raised by the department',
      caseId: '', // Will be set after case creation
      clientId: '', // Will be set after client creation
      caseNumber: '', // Will be set after case creation
      stage: 'Scrutiny',
      priority: 'High',
      status: 'Not Started',
      assignedToId: '1',
      assignedToName: 'John Smith',
      assignedById: '3',
      assignedByName: 'Mike Wilson',
      createdDate: currentDate.toISOString().split('T')[0],
      dueDate: futureDate(10),
      estimatedHours: 8,
      isAutoGenerated: false,
      escalationLevel: 0
    }
  };
};